### ISSUE TITLE
Add unit and e2e tests for the HelpSection component

### ISSUE THREAD

**Issue by akmadian** [creativecommons/chooser#116]
Unit and e2e tests need to be written for the HelpSection component. Unit tests are done with [Jest](https://jestjs.io/), and e2e tests are done with [nightwatch](https://nightwatchjs.org/).

Please remember to test the following things:
- That individual parts of the component are present when appropriate. (unit and e2e)
- That any computed props and methods work properly, if there are any. (unit)
- Any common interactions between the user and component, if there are any. (e2e)
- Any other functionality that is unique to the component being tested!

### Additional Context
- [./src/components/HelpSection.vue](https://github.com/creativecommons/cc-chooser/blob/master/src/components/HelpSection.vue)
- [This repo's testing README](https://github.com/creativecommons/cc-chooser/blob/master/tests/README.md)
- [Vue's guide on unit testing](https://vuejs.org/v2/guide/unit-testing.html)
- [Vue's guide on unit testing with VueX](https://vue-test-utils.vuejs.org/guides/using-with-vuex.html)

**Comment by kushaggarwal** [comment]
Hello @akmadian I would like to go for this but I am not fully aware as how to proceed so can you please give me a few pointers for same
Thank you

**Comment by akmadian** [comment]
Hey @kushaggarwal, I would recommend doing some research on what unit and e2e (end to end) testing is, and how it works. Once you're familiar with the concept of testing and tests, your task is to think of some tests (I've included a general list of things to look at when coming up with tests in the main issue body), and write the code for the tests you've come up with (Vue's guide on unit testing, and the documentation for Jest and Nightwatch will be helpful with this). 

I would also recommend looking through the `tests` directory of this repo to familiarize yourself with how the code is organized.

I could help find some resources about testing for you, but I highly recommend that you try to figure it out on your own first. In the meantime, I'll assign this issue to you. If you've got any questions, please feel free to ask!

**Comment by kushaggarwal** [comment]
Okay @akmadian thank you very much for your help will start working towards the same

**Comment by hemanth-hk** [comment]
@kushaggarwal I found an error in the `HelpSection.vue` component

![HelpSection](https://user-images.githubusercontent.com/43946715/76164982-39fc6200-6179-11ea-956f-304b5984fc34.png)

Please ask your mentor to include this in your `PR` or please inform me so that I'll make an issue

**Comment by akmadian** [comment]
@hemanth-hk This will be fixed in #129

**Comment by hemanth-hk** [comment]
Any help @kushaggarwal?

**Comment by akmadian** [comment]
@hemanth-hk I don't see any progress on @kushaggarwal's fork, so I'm gonna open this up to other contributors, if you'd like to work on this, you can go ahead since it's now free!

**Comment by kushaggarwal** [comment]
Hello @akmadian apologies for this delay 
Actually I was caught up with my university exams hence wasn't able to attend to this issue

**Comment by kushaggarwal** [comment]
@hemanth-hk please continue for the same
Thank you

**Comment by akmadian** [comment]
No worries @kushaggarwal, I'm also very busy with exams right now :)

**Comment by hemanth-hk** [comment]
I submitted a `PR` for this issue, before submitting I saw @kushaggarwal's fork and it didn't had any progress.
I'm sorry if @kushaggarwal was working on this.
