### ISSUE TITLE
Add unit and e2e tests for the LicenseDropdown component

### ISSUE THREAD

**Issue by akmadian** [creativecommons/chooser#120]
Unit and e2e tests need to be written for the LicenseDropdown component. Unit tests are done with [Jest](https://jestjs.io/), and e2e tests are done with [nightwatch](https://nightwatchjs.org/).

Please remember to test the following things:
- That individual parts of the component are present when appropriate. (unit and e2e)
- That any computed props and methods work properly, if there are any. (unit)
- Any common interactions between the user and component, if there are any. (e2e)
- Any other functionality unique to the component being tested!

### Additional Context
- [./src/components/LicenseDropdown.vue](https://github.com/creativecommons/cc-chooser/blob/master/src/components/LicenseDropdown.vue)
- [This repo's testing README](https://github.com/creativecommons/cc-chooser/blob/master/tests/README.md)
- [Vue's guide on unit testing](https://vuejs.org/v2/guide/unit-testing.html)
- [Vue's guide on unit testing with VueX](https://vue-test-utils.vuejs.org/guides/using-with-vuex.html)

**Comment by abhisheknaiidu** [comment]
Want to work on this.

**Comment by akmadian** [comment]
Go ahead @abhisheknaiidu :)

**Comment by hemanth-hk** [comment]
Any help @abhisheknaiidu?

**Comment by abhisheknaiidu** [comment]
@hemanth-hk you can work on this if you want. Right now, I am just contributing to CC Search repo as I wanted to contribute to their codebase as much as can.

**Comment by hemanth-hk** [comment]
@abhisheknaiidu I have already submitted 2 PR's, If you are stuck anywhere I can help you

**Comment by abhisheknaiidu** [comment]
@hemanth-hk Thanks, but I haven't yet started working on this, As I said earlier, if you want, you can work on this :)

**Comment by akmadian** [comment]
I'm gonna free this issue up to other contributors. @hemanth-hk since you've already had a couple PRs merged, let's wait for a few days to see if anyone wants to take this up. If noone indicates their interest, you can go ahead :)

**Comment by Tanmay1201** [comment]
Hey @akmadian! Can i work on this?

**Comment by akmadian** [comment]
go ahead @Tanmay1201! As per [our new code contribution guidelines](https://opensource.creativecommons.org/contributing-code/), you don't need to ask for permission to work on an issue, you can just submit a PR. It's best to state that you're working on the issue before starting work, though :)

**Comment by codetheorem** [comment]
assign this to me.

**Comment by obulat** [comment]
> assign this to me.

Go ahead!
