### ISSUE TITLE
Add unit and e2e tests for the LicenseUseCard component

### ISSUE THREAD

**Issue by akmadian** [creativecommons/chooser#121]
Unit and e2e tests need to be written for the LicenseUseCard component. Unit tests are done with [Jest](https://jestjs.io/), and e2e tests are done with [nightwatch](https://nightwatchjs.org/).

Please remember to test the following things:
- That individual parts of the component are present when appropriate. (unit and e2e)
- That any computed props and methods work properly, if there are any. (unit)
- Any common interactions between the user and component, if there are any. (e2e)
- Any other functionality unique to the component being tested!

### Additional Context
- [./src/components/LicenseUseCard.vue](https://github.com/creativecommons/cc-chooser/blob/master/src/components/LicenseUseCard.vue)
- [This repo's testing README](https://github.com/creativecommons/cc-chooser/blob/master/tests/README.md)
- [Vue's guide on unit testing](https://vuejs.org/v2/guide/unit-testing.html)
- [Vue's guide on unit testing with VueX](https://vue-test-utils.vuejs.org/guides/using-with-vuex.html)

**Comment by hemanth-hk** [comment]
Can I work on this?

**Comment by akmadian** [comment]
@hemanth-hk I'm gonna say no since you've already submitted 2 PRs, let's make sure that others can contribute as well :)

**Comment by hemanth-hk** [comment]
Okay... I have a small request , when you review my PRs please give me some feedback about how I wrote tests cause I never wrote tests before

**Comment by hemanth-hk** [comment]
Its been a long time and no one showed any interest so I am working on this :)

**Comment by obulat** [comment]
This issue has been solved.
