### ISSUE TITLE
Add unit and e2e tests for the App component

### ISSUE THREAD

**Issue by akmadian** [creativecommons/chooser#124]
Unit and e2e tests need to be written for the App component. Unit tests are done with [Jest](https://jestjs.io/), and e2e tests are done with [nightwatch](https://nightwatchjs.org/).

Please remember to test the following things:
- That individual parts of the component are present when appropriate. (unit and e2e)
- That any computed props and methods work properly, if there are any. (unit)
- Any common interactions between the user and component, if there are any. (e2e)
- Any other functionality unique to the component being tested!

### Additional Context
- [./src/App.vue](https://github.com/creativecommons/cc-chooser/blob/master/src/App.vue)
- [This repo's testing README](https://github.com/creativecommons/cc-chooser/blob/master/tests/README.md)
- [Vue's guide on unit testing](https://vuejs.org/v2/guide/unit-testing.html)
- [Vue's guide on unit testing with VueX](https://vue-test-utils.vuejs.org/guides/using-with-vuex.html)

**Comment by achilep** [comment]
hello please i will like to work o this issue

**Comment by akmadian** [comment]
@achilep go ahead!

**Comment by achilep** [comment]
Thank you

**Comment by achilep** [comment]
please can cheek my pr

**Comment by JackieBinya** [comment]
@akmadian and @obulat 
May I contribute to this issue.

**Comment by achilep** [comment]
Do you have any suggestions @JackieBinya

**Comment by JackieBinya** [comment]
Hey @achilep what's the status of this issue, is it closed?
If not sure I do have ideas.
But please clarify for me.
