### ISSUE TITLE
Add unit tests for license-uitilities.js

### ISSUE THREAD

**Issue by akmadian** [creativecommons/chooser#125]
Unit tests need to be written for license-utilities.js. Unit tests are done with [Jest](https://jestjs.io/).

Please remember to test the following things:
- All methods, being sure to test a range of inputs for each method, including edge cases.

### Additional Context
- [./src/utils/license-utilities.js](https://github.com/creativecommons/cc-chooser/blob/master/src/utils/license-utilities.js)
- [This repo's testing README](https://github.com/creativecommons/cc-chooser/blob/master/tests/README.md)
- [Vue's guide on unit testing](https://vuejs.org/v2/guide/unit-testing.html)
- [Vue's guide on unit testing with VueX](https://vue-test-utils.vuejs.org/guides/using-with-vuex.html)

**Comment by acagastya** [comment]
Hello.  Could I work on the test coverages?

**Comment by akmadian** [comment]
Go ahead! @acagastya

**Comment by acagastya** [comment]
@akmadian Hi.  Could you please tell me how to organise the tests?  In which directory am I supposed to put it under?

**Comment by akmadian** [comment]
It should be organized similarly to how component tests are organized. Just like component unit tests go in `./tests/unit/specs/components/`, unit test specs for utils should go in `./tests/unit/specs/utils/`

**Comment by acagastya** [comment]
Okay, thank you.  :-)
I have already started, and I will move it to the appropriate folder now.

**Comment by acagastya** [comment]
@akmadian While writing the tests, I just realised, the function `attrToFull`, which takes an object as a parameter, and outputs license string gives a wrong answer for this object: `{ BY: true, ND: true, SA: true }`.  Non-Deriv is mutually exclusive from ShareAlike.  Right now, its result is `Attribution-NonDerivatives 4.0 International` (CC BY-ND 4.0).

Do we assume the parameters passed to the function will correspond to a valid license?  Or should the function return an error?

**Comment by akmadian** [comment]
I think it's safe to assume that the ND and SA incompatability won't be an issue, the ability to make a selection for SA is disabled when ND is selected, so it's theoretically impossible for that specific configuration to get passed in.

So, to answer your question directly, it's safe to assume that the parameters passed will correspond to a valid license.

**Comment by acagastya** [comment]
Thank you for the swift response, @akmadian.  I found another oddity.  
`attrToFull({ BY: undefined}) //? CC0 1.0 Universal`  
`attrToShort({ BY: undefined}) //? undefined`

Is that how they are supposed to behave?

**Comment by akmadian** [comment]
Thanks for catching this, I would say that for now, yes, this is expected behavior. The person who wrote this code is @obulat, and she's gonna be unavailable for a while, and I'm unsure if this is expected behavior.

Let's assume that this behavior is expected for now, and we can re-examine once @obulat is back :)

**Comment by acagastya** [comment]
Okay, point noted.  And I have duly updated the tests.  Thank you for letting me know.

**Comment by acagastya** [comment]
@akmadian I had been thinking of edge cases, and unsurprisingly, `shortToAttr('AND')`'s result is CC BY-ND, because it matches `"ND"`.  Should I assume the input to `shortToAttr` would always be the correct short-hand notation of the CC licenses?

**Comment by akmadian** [comment]
Yes, I think that's safe to assume

**Comment by obulat** [comment]
> `attrToFull({ BY: undefined}) //? CC0 1.0 Universal`
> `attrToShort({ BY: undefined}) //? undefined`
> 
> Is that how they are supposed to behave?
Thank you for catching this issue, @acagastya !
At first, we had CC BY license set by default, and all attributes were set to false (except for BY, which was set to true) at the beginning. Then we decided not to have a default license choice, so all attributes became `undefined` at the start, and the function `attrToShort` was changed to return `undefined` if no selection had been made. This `undefined` value is actually used in the dropdown step to show placeholder value if no license had been selected. 
However, I forgot to update the `attrToFull`.

Could you update `attrToFull` in accordance with `attrToShort`?

**Comment by acagastya** [comment]
@obulat Sure thing, I will do that.  And update the tests accordingly.  Thank you for letting me know the context.

And I agree with your way of approaching this.  Creative Commons licenses (especially version 4.0) are very clear about the requirements and explicitly state what is true, what is defined.  If something is not defined (and marked as `undefined`), it is not to be treated as `false`.  If it was `false`, it must be set explicitly.

**Comment by acagastya** [comment]
Hi, I am sorry for the delay.  I will be submitting the PR in a few hours.

**Comment by acagastya** [comment]
@obulat Just a quick clarification, what should be the output of `licenseIconsArr({ BY: undefined })`.  Should it be empty array.  Or should I assume it is not possible to have that?
