### ISSUE TITLE
Improve unit and e2e tests for the Stepper component

### ISSUE THREAD

**Issue by akmadian** [creativecommons/chooser#126]
Unit and e2e tests need to be improved for the Stepper component. Unit tests are done with [Jest](https://jestjs.io/), and e2e tests are done with [nightwatch](https://nightwatchjs.org/).

Please remember to test the following things:
- That individual parts of the component are present when appropriate. (unit and e2e)
- That any computed props and methods work properly, if there are any. (unit)
- Any common interactions between the user and component, if there are any. (e2e)
- Any other functionality unique to the component being tested!

### Additional Context
- [./src/components/Stepper.vue](https://github.com/creativecommons/cc-chooser/blob/master/src/components/Stepper.vue)
- [This repo's testing README](https://github.com/creativecommons/cc-chooser/blob/master/tests/README.md)
- [Vue's guide on unit testing](https://vuejs.org/v2/guide/unit-testing.html)
- [Vue's guide on unit testing with VueX](https://vue-test-utils.vuejs.org/guides/using-with-vuex.html)

**Comment by JackieBinya** [comment]
Hello @Ari.
May I please work on this issue.

**Comment by akmadian** [comment]
@JackieBinya go ahead!
