### ISSUE TITLE
language logo appear in How do the Licenses Work?  under CONFUSED? NEED HELP?  session

### ISSUE THREAD

**Issue by achilep** [creativecommons/chooser#140]
## Describe the bug
language logo appear in the in "how do the licenses work" question under confused?need help? 

## To Reproduce

1. Go to 'CONFUSED? NEED HELP?'
2. Click on 'How do the Licenses Work? '
3. Scroll down 
4. See error:'the logo language appear'

## Expected behavior
the logo language should not appear

## Screenshots
![Screenshot from 2020-03-17 17-21-31](https://user-images.githubusercontent.com/39851246/76877945-677d9580-6874-11ea-80b4-8ac460814f34.png)

## Desktop
 - OS: (ex. iOS)
 - Browser (ex. chrome, safari)

## Smartphone 
 - Device: (ex. iPhone6)
 - OS: (ex. iOS8.1)
 - Browser (ex. stock browser, safari)
 - Version (ex. 22)

**Comment by achilep** [comment]
Hello @akmadian  please can change the stare of this issue to help wanted I will like to work on it. Thank you

**Comment by akmadian** [comment]
Thanks for reporting this! If you'd like to work on a fix for this, go ahead!

**Comment by kss682** [comment]
@akmadian @achilep logo is getting overlayed over the other questions too.

![Screenshot from 2020-03-20 21-27-33](https://user-images.githubusercontent.com/30746998/77182117-432eec80-6af2-11ea-8e4f-5b049b07016f.png)

and  its not a problem when browser is in full screen(f11).

![Screenshot from 2020-03-20 21-33-00](https://user-images.githubusercontent.com/30746998/77182255-76717b80-6af2-11ea-982d-0ca9ac6c3e72.png)

**Comment by achilep** [comment]
Yes i am actually working on it

**Comment by achilep** [comment]
Any suggestions

**Comment by kss682** [comment]
@achilep have not actually looked into much , seems like you can start looking into HelperSection.vue, in components.

**Comment by JordanRuetz** [comment]
Issue seems inactive, I am going to take it up.

**Comment by achilep** [comment]
Great work. Sorry for late reply I have some issue.
