### ISSUE TITLE
Update location that CC license icons are served from

### ISSUE THREAD

**Issue by kgodey** [creativecommons/chooser#141]
## Description
CC license icons in the chooser need to be served from the same location as the icons on https://creativecommons.org/about/downloads (https://mirrors.creativecommons.org). We should use a query string parameter to indicate that traffic is coming from the chooser.

e.g. the CC icon could use the URL https://mirrors.creativecommons.org/presskit/icons/cc.svg?chooser-v1

**Comment by obulat** [comment]
@kgodey , I started working on this issue, but I have a question regarding the link:
In the links that we have currently, the parameter in url is added with 'ref=', and in link you gave above doesn't have the 'ref='. Which one should we use?

-  https://mirrors.creativecommons.org/presskit/icons/cc.svg?chooser-v1
-  https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1

**Comment by kgodey** [comment]
We should use the "ref", thanks for spotting that.
