### ISSUE TITLE
Custom Test Utils file for unit tests for a DRY approach

### ISSUE THREAD

**Issue by hemanth-hk** [creativecommons/chooser#143]
## Problem Description
Presently the unit and e2e tests are written without using any type of test_util file which is a repetitive task.

## Solution Description
Make a custom test_util file which contains most of the repetitive functions and anyone can import and write tests in a more `DRY` approach

## Additional context
* This issue is only for unit tests

Before working on it I have some queries
1. Please suggest a name for the file, I have `customUnitTestUtils.js` in my mind
2. Does changing the present unit tests to fit with this change, come under the scope of this issue?

Once my queries are cleared I will immediately start working on this :)

**Comment by akmadian** [comment]
Please elaborate on what exactly would go in the file, would it be mock vuex configs, mock states, methods, etc? I'll mark as `ticket work required` until you respond

**Comment by hemanth-hk** [comment]
Ya sure, my bad :(

**Comment by hemanth-hk** [comment]
Okay so here is what I wanted to do with this file

``` javascript
// After the basic scaffolding is done and we import this file

// In the before each
Component = new customUnitTestUtils(wrapper,expect)

// Tests start here
    it('Check if the component is rendered', () => {
        Component.isVue()
    })
    it('Check if it has the "some" class element', () => {
        Component.domHas('.some')
    })
```
Something like the above would be great and making like that is my idea
Basically this file will have a class and the constructor will take the wrapper and expect
```javascript
// File will look something like this
class customUnitTestUtils {
 constructor(wrapper, expect) {
    this.wrapper = wrapper
    this.expect = expect
  }
  isVue(){
    this.expect(wrapper.isVueInstance()).toBeTruthy()
  }
  domHas(selector) {
    this.expect(this.wrapper.contains(selector)).toBe(true)
  }
}
// export
```
I hope this explains it and while explaining this I felt `TestHelpers` would be a better name for the file

**Comment by Cronus1007** [comment]
@hemanth-hk  Are you currently working on this issue. If not shall I take over this issue.

**Comment by obulat** [comment]
Closing this issue as not relevant now.
