### ISSUE TITLE
FirstStep Component unit tests failing

### ISSUE THREAD

**Issue by JackieBinya** [creativecommons/chooser#148]
## Describe the bug

- The unit tests for the FirstStep component are failing.
- e2e tests are missing
## To Reproduce

1. Run tests in the FirstStep.spec.js file by typing the command 
```npm run test:unit FirstStep.spec.js```
2. On the terminal, you will get the error message that says that the test suite failed to run as shown in the screenshot below.

## Expected behavior

- All unit tests must pass

## Screenshots

![Screenshot from 2020-03-30 20-52-56](https://user-images.githubusercontent.com/50267279/77950546-edfc9300-72c8-11ea-8327-c4dce414ac61.png)

## Desktop (please complete the following information)
 - OS: (ex. iOS) : Ubuntu
 - Browser (ex. chrome, safari): N/A
 - Version (ex. 22): 

## Smartphone (please complete the following information)
 - Device: (ex. iPhone6): N/A
 - OS: (ex. iOS8.1): N/A
 - Browser (ex. stock browser, safari): N/A
 - Version (ex. 22): 19.10

## Additional context

- N/A

**Comment by hemanth-hk** [comment]
I see that the `FirstStep.vue` doesn't have even the e2e tests and the unit tests need to be updated so it would be better if you create an issue for both unit and e2e like all other components and solve this thing here itself. This would be better I believe

Let's see what **Ari** or other members say about this

**Comment by JackieBinya** [comment]
I hadn't realized that the e2e tests are missing.
Opened a PR already just completed the unit tests PR #149 
I guess I would then have to update it and add e2e tests. 
Waiting for @akmadian for the go-ahead

**Comment by hemanth-hk** [comment]
You can always append to that PR

**Comment by Tanmay1201** [comment]
@JackieBinya I see that there is a configuration error. On my machine this test file seems to run fine without displaying any error :)

**Comment by JackieBinya** [comment]
@Tanmay1201 hi 
I'm pretty new at this. 
Sorry about the delay.
Well I saw that file was misplaced and the issue of file configuration and the issue of coverage and the issue of missing e2e tests
I made an attempt to solve all those issues  on PR #149
At this point I am not really sure what can be done. 
But for intest sake please check out my implementation on my PR

I've checked yours out.

**Comment by obulat** [comment]
I've moved the `FirstStep.spec.js` to "unit/specs/components" folder and edited the import to '@/**c**omponents' to solve this issue, so I am closing it. I will make more comments re: FirstStep tests in the corresponding PRs.
