### ISSUE TITLE
Updates to "Confused? Need Help?" questions

### ISSUE THREAD

**Issue by annatuma** [creativecommons/chooser#151]
## Problem Description
We have finalized the language for the "Confused? Need Help?" questions on the Chooser.

## Solution Description
Each question, and _approved_ answer, is detailed below. The text should simply be swapped out. There is one new question that needs to be added. Please note, all links should open in a new tab. Links are indicated with <text: URL> placeholders. Icons are indicated with (icon) placeholders.

Q: What Are Creative Commons Licenses?
A: Creative Commons legal tools give everyone from individual creators to large companies a simple, standardized way to grant copyright permissions to their creative work. They are designed to forge a balance inside the traditional "all rights reserved" setting that copyright law creates. For more information, please see <About the Licenses: https://creativecommons.org/licenses/>

Q: How do the Licenses Work?
A: There are six different Creative Commons licenses, as well as one public domain dedication tool. Creators choose the option that is right for them, and then apply that license to their copyrighted work. Anyone who wants to reuse the work of the creator in a manner that requires permission under copyright must comply with the terms of the license.  For more information, please see <About the Licenses: https://creativecommons.org/licenses/>

Q: What do the Icons Mean?
A: The icons represent key features of the different CC license options:

BY (icon) - Credit must be given to you, the creator.
SA (icon) - Adaptations must be shared under the same terms.
NC (icon) - Only noncommercial use of your work is permitted.
ND (icon) - No derivatives or adaptations of your work are permitted.

Q: Considerations Before Licensing
_No edits required to this question_

Q: How do I Formally License my Work?
Licensing your work is as simple as marking it under the specific license you choose. This marking can be as simple as a bit of text stating the license in a copyright notice, or as complex as embedding the license information on your website using the HTML code associated with the particular license. We strongly recommend at least including a link to the applicable license. 

Q: The Six Creative Commons Licenses
_No edits required to this question_

Q: How are Licenses Communicated?
_No edits required to this question_

Q: What is a Free Culture License?
_No edits required to this question_

Q: Looking for Earlier License Versions, including Ports? **(this is a new question)**
A: The most recent license version is 4.0, which can be used internationally. Earlier versions of licenses, including 3.0 international and ports localized to particular jurisdictions, can still be used on the legacy version of the <License Chooser: https://creativecommons.org/choose/#>[open in new tab]. Click on the link at the top of the page <b>"Looking for earlier license versions, including ports?"</b> and follow the prompts to use earlier license versions.

**Comment by sjs8906** [comment]
@annatuma I'd love to help with this.

**Comment by kgodey** [comment]
@sjs8906 go ahead

**Comment by hemanth-hk** [comment]
@sjs8906 I wrote tests for the `HelpSection.vue` or the "Confused? Need Help?" section so once you are done with the changes please run `npm run test:unit` and see if anything breaks, As far as I know, tests should not break cause most of the part is handled by $t but do let me know if anything breaks I would be happy to fix them

**Comment by SaurabhAgarwala** [comment]
@sjs8906 Are you still working on this?
If not, I would like to take upon this issue

**Comment by SaurabhAgarwala** [comment]
@kgodey Shall I go ahead and work on this?

**Comment by kgodey** [comment]
@SaurabhAgarwala go ahead, you don't need our permission for issues marked "help wanted".

**Comment by SaurabhAgarwala** [comment]
@annatuma For the new question to be added, what I understand from the context of the last two lines is that there should also be a link in the heading **"Looking for earlier license versions, including ports?"** which redirects to [this](https://creativecommons.org/choose/) page. But you have not mentioned inserting any link in the heading. Can you please look into it and clarify.

**Comment by annatuma** [comment]
@SaurabhAgarwala that text should just be bolded, which is why it was bolded in the ticket. The only link for that question is indicated with <parentheses>.
