### ISSUE TITLE
Error in CopyrightWaiverStep.js e2e test

### ISSUE THREAD

**Issue by hemanth-hk** [creativecommons/chooser#156]
## Describe the bug
The below screenshot describes it all basically one of the e2e tests fails due to clickHandler error on the `.select` class

## To Reproduce
clone and run `npm run test` or `npm run test:e2e`

## Expected behavior
No tests should fail 

## Screenshots
![copyrighte2e](https://user-images.githubusercontent.com/43946715/78473381-e3754a00-775d-11ea-9aa0-b06fd4272fcb.png)

## Desktop (please complete the following information)
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.162

## Additional context
For the same error, some of my previous tests were failing

I want to work on this but before that, I need a confirmation if they are really breaking or not :)

**Comment by JackieBinya** [comment]
Hey @hemanth-hk may you please elaborate what you mean in the *Additional Context*, when you say _for the same error your previous tests were also failing_.

**Comment by hemanth-hk** [comment]
I wrote some tests for the `LicenseCode.vue` and `LicenseDetailsCard.vue` components and suddenly they broke and I had to send a `PR` fixing them, basically the `.select > select` is not able to handle the click event so we have to click only the `.select`. Then I noticed that the same thing is happening in the `CopyrightWaiverStep.vue` tests, so I created this issue

@obulat knows about this so I provided the description briefly. Hope this explains in a better way :)

**Comment by JackieBinya** [comment]
@hemanth-hk Thanks for the explanation.
I hadn't even noticed that because locally the e2e were passing.
I will now also take a look at them closely, thanks for the heads up!
If I come up with anything I will let you know.

**Comment by obulat** [comment]
This error has been fixed, I'm closing the issue.
