### ISSUE TITLE
CC Logo stacks above the modal window

### ISSUE THREAD

**Issue by SaurabhAgarwala** [creativecommons/chooser#159]
## Describe the bug
The CC Logo present in the footer gets stacked above the modal window opened when a "Confused? Need Help?" question is clicked, hence affecting the view of the modal window contents.

## To Reproduce

1. Go to [License Chooser Website](https://chooser-beta.creativecommons.org/)
2. Scroll to the bottom of the page
3. Click on any of the following questions: 
    - How do the Licenses Work?
    - What do the Icons Mean?
    -  How do I Formally License my Work?
    - The Six Creative Commons Licenses.

## Expected behavior

The part of the CC Logo overlapping with the modal window should be hidden behind the modal window.

## Screenshots

![CC_Issue](https://user-images.githubusercontent.com/32371951/79346623-36b27e00-7f50-11ea-8288-12593d868248.jpeg)

## Desktop (plase complete the following information)
 - OS: Ubuntu 18.04 LTS 
 - Browser: Google Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

# Additional Context
The error may be resolved by setting an appropriate z-index value for the modal window

**Comment by akmadian** [comment]
I'm going to close this because we'll be replacing the current footer with the one from Vocabulary in the near future and this will likely be made obsolete.

**Comment by obulat** [comment]
This is not, actually, an issue with the footer, but with modals, and is fixed by #186. This issue is part of #165 .

**Comment by obulat** [comment]
Fixed via #171
