### ISSUE TITLE
Update CC Chooser product logo

### ISSUE THREAD

**Issue by annatuma** [creativecommons/chooser#160]
CC Chooser has an updated product logo. We'd like to update it in the header of the site.

Note, this is blocked by pending updates of the logos in Vocabulary:
https://github.com/creativecommons/vocabulary/issues/360

**Comment by dhruvkb** [comment]
@annatuma @akmadian just informing that creativecommons/vocabulary#360 is resolved by creativecommons/vocabulary#366 so this can move forward.
