### ISSUE TITLE
Update Footer on Chooser to Vocabulary

### ISSUE THREAD

**Issue by annatuma** [creativecommons/chooser#161]
The footer on the License Chooser does not currently match the footer in Vocabulary. (It is possible this was implemented before the footer was available in Vocabulary?)

We should update the design to use the footer from Vocabulary. The only nav item in the footer should be the Feedback form link.

**Comment by Herald-Of-Solace** [comment]
Can I work on this?

**Comment by kgodey** [comment]
@Herald-Of-Solace no need to ask for permission, go ahead.

**Comment by Herald-Of-Solace** [comment]
@kgodey Thanks

**Comment by obulat** [comment]
Yes, Anna, when I added the footer, it wasn't ready in Vocabulary just yet. 
I looked into Vue Vocabulary now, but the Footer component there isn't ready yet. So, I copied footer from the cccatalog, please see in #169. Does Feedback look ok? Should it open in a new tab, or the same tab?
