### ISSUE TITLE
Header and background updates

### ISSUE THREAD

**Issue by annatuma** [creativecommons/chooser#162]
There are a couple of small changes needed to the License Chooser, to get it to match [the original mockups](https://www.figma.com/file/Gmr57huMk646K1G6boePoO/Mockup-v2?node-id=91%3A0).

1) The background color of the body should be light grey.

2) The header should use Vocabulary (may not be doing that, given timing), and the Feedback link in the header should include an external link icon.

**Comment by JackieBinya** [comment]
@annatuma I could not access the mockups. This is the message I got from figma
![new](https://user-images.githubusercontent.com/50267279/81574522-35853d00-93a6-11ea-83c5-43d1ce5e6996.png)

**Comment by annatuma** [comment]
So sorry @JackieBinya I've fixed the link. I forgot to double check the settings. Let me know if you have any other issues with it.
