### ISSUE TITLE
Incorrect usage of the rel attribute

### ISSUE THREAD

**Issue by fkohrt** [creativecommons/chooser#188]
## Description

To the best of my RDFa knowledge, the object of the `rel` attribute is the `href` attribute and __not__ the inner content of its tag (sources: [1](https://stackoverflow.com/a/18853626), [2](https://www.ctrl.blog/entry/rdfa-link-attributes.html)). The latter is, however, implied by the following code fragments:

https://github.com/creativecommons/chooser/blob/40dcfa047ef50fa82d0431a61f38e824d2f04a57/src/utils/license-utilities.js#L157

https://github.com/creativecommons/chooser/blob/40dcfa047ef50fa82d0431a61f38e824d2f04a57/src/components/LicenseCode.vue#L103

https://github.com/creativecommons/chooser/blob/40dcfa047ef50fa82d0431a61f38e824d2f04a57/src/components/LicenseCode.vue#L11-L32

https://github.com/creativecommons/chooser/blob/f094cf0ba8972f0d812fd365ec636a7287e7f6f8/tests/unit/specs/components/LicenseCode.spec.js#L69

(And several times inside [`tests/unit/specs/utils/license-uilities.test.js`](https://github.com/creativecommons/chooser/blob/e05c8a6b556948d945321eef008e2f4cc2cbc082/tests/unit/specs/utils/license-uilities.test.js).)

## Expectation

The `property` attribute should be used instead.

**Comment by obulat** [comment]
Thank you for bringing this up, @fkohrt ! It is great to have input on RDFa properties. I will review your PR tomorrow.
