### ISSUE TITLE
Firefox not scrolling up before info modal appears

### ISSUE THREAD

**Issue by fkohrt** [creativecommons/chooser#192]
## Description

Clicking a question inside the help section ("CONFUSED? NEED HELP?") won't reveal the answer if scrolled down, i.e. it's not being scrolled up automatically. Scrolling manually doesn't work now.

## Reproduction

1. Visit the [chooser](https://chooser-beta.creativecommons.org/) on Firefox.
2. Click through until you can provide attribution details.
3. Scroll to the bottom.
4. Click on one of the questions.
5. Notice the outlined behaviour.

## Expectation

The window should scroll up before the modal appears.

## Screenshots

![wrong](https://user-images.githubusercontent.com/12914806/96508570-16df7800-125b-11eb-871f-8d4757ca7039.png)

## Environment

 - Device: Laptop
 - OS: Fedora 31
 - Browser: Firefox
 - Version: 81.0.1

**Comment by obulat** [comment]
Thank you for reporting this bug! It needs fixing.

**Comment by zackkrida** [comment]
As discussed with @obulat, we plan to fix this by moving the modal component inside of https://github.com/creativecommons/cccatalog-frontend into vocabulary, and switching away from the buefy modals.

**Comment by obulat** [comment]
The new modal has been implemented, and from what I can see in Firefox, the problem has been solved (although not deployed yet).
