### ISSUE TITLE
Placeholders contain domain names, not URLs

### ISSUE THREAD

**Issue by fkohrt** [creativecommons/chooser#193]
## Description

The attribution details currently suggest that one can enter a domain name. This will, however, result in an address relative to the chooser's domain. I therefore suggest to add protocols to the placeholder to make them full URLs.

https://github.com/creativecommons/chooser/blob/e0d79d68611c93d52035013e3164715f268b75ac/tests/e2e/specs/LicenseCode.js#L20-L30

https://github.com/creativecommons/chooser/blob/f094cf0ba8972f0d812fd365ec636a7287e7f6f8/tests/unit/specs/components/LicenseCode.spec.js#L19-L21

https://github.com/creativecommons/chooser/blob/f094cf0ba8972f0d812fd365ec636a7287e7f6f8/tests/unit/specs/components/LicenseCode.spec.js#L75-L83

https://github.com/creativecommons/chooser/blob/40dcfa047ef50fa82d0431a61f38e824d2f04a57/src/locales/en.json#L74-L85

https://github.com/creativecommons/chooser/blob/e0d79d68611c93d52035013e3164715f268b75ac/src/locales/ru.json#L74-L85

And several times in [`tests/unit/specs/utils/license-uilities.test.js`](https://github.com/creativecommons/chooser/blob/e05c8a6b556948d945321eef008e2f4cc2cbc082/tests/unit/specs/utils/license-uilities.test.js).

Another (additional) possibility could be to change the input type to `url`.

## Reproduction

Enter a domain name (as suggested) inside the attribution details and see where the created link goes to.

## Expectation

A full URL should be visible in the placeholder.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Aspie96** [comment]
I agree this is a bug.
