### ISSUE TITLE
Inconsistent wording for attribution details

### ISSUE THREAD

**Issue by fkohrt** [creativecommons/chooser#198]
## Description

The attribution details currently have the entries "Work Author" and "URL of creator profile", making it harder to connect the two entries.

## Expectation

"URL of creator profile" → "URL of author profile"

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by obulat** [comment]
Thank you for reporting this! We will change the wording and the order of the fields soon.

**Comment by zackkrida** [comment]
@obulat @fkohrt Here is the chosen language:

## Label (Input Placeholder)

- Creator of Work (Jane Doe)
- Title of Work (e.g. Best Photo Ever)
- Link to Work(e.g. https://janedoe.com/best-photo-ever)
- Link to Creator Profile (e.g. https://janedoe.com)
