### ISSUE TITLE
Anonymized feedback from user

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/chooser#203]
Here is some feedback I received from a community member. Perhaps most relevant to @annatuma and @pachovm in preparation for a redesign.

> Thank you for sharing that beta chooser. I think it has a great flow, though I'm not disoriented by the process in general (so I'm not a stress case). 
> 
> Here's some (hopefully constructive) feedback, if you don't mind.
> 
> Re: steps.
> In a scenario where the creator is choosing to use the chooser, I think you've got the correct 1st step.
> 
> In the scenario I experienced, where the creator is being persuaded to use the chooser, maybe a 1st step should dead-simple explain why CC is better than [doing nothing / assuming work is sharable]
> 
> 
> For instance, (1) no license means restricted, (2) academia won't use the artwork if the creator employs a self-made license. 
> 
> Re: consequences.
> This relates to the 'academia as a user' problem (2) mentioned above. 
> 
> More generally, and throughout the various steps, it's good to know some broad stroke consequences of picking choice A over choice B. 
> 
> For instance, I was in a workshop and counsel told us we should stay away from open source because it could be a 'poison pill' for the entire ITIP infrastructure. They said this because they had to kill at least one lucrative deal far along the transaction because late stage due diligence found a CC-type license disallowing commerciality that, in a sense, infected all of the company's sweat of the brow. 
> 
> My business model relies on open source so I can't take that advice whole hog but it would be good if the consequences of non-commercial were much clearer, for the licensor and licensee. In addition to the chooser, perhaps your icons could use different colours to indicate watch out, it's non-commercial! 
> 
> Re: types.
> This is maybe a problem for program authors only, not other types of IP. However, being the way we automate machines, program scripts are arguably the most powerful type of IP out there (heading into the future, especially if code literacy is democratized). 
> 
> Your chooser is for all types of copyright, I believe. Looking at the chooser, it isn't clear it's for copyright only. I think you contemplate patent rights in some of your licenses. So, maybe I'm wrong. 
> 
> Maybe this should be the 0th step: What's the artwork type?

**Comment by annatuma** [comment]
Fantastic, thanks for reporting this! I've got it documented with all the other written feedback we've received, all of which we'll be reviewing today.
