### ISSUE TITLE
ShareALike does not remove when changing the answer

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#208]
## Description
When answering `Yes. Others can remix, adapt, or build upon my work` in Q4. Then when users reach the Q5 but back to Q4 to select `No. Others may only use my work in unadapted form.`, the **SA icon and meaning bullet** does not remove from the Recommended License section.

## Expectation
The **SA icon and definition** should remove from the Recommended License section. 

## Screenshots
<img width="1347" alt="Screen Shot 2020-11-18 at 10 22 17" src="https://user-images.githubusercontent.com/895819/99536120-ac6c4580-2988-11eb-8309-dee66e05c85c.png">

**Comment by obulat** [comment]
I couldn't reproduce this on chooser-beta:
![de8eab831b562885dc923d451bedd29a](https://user-images.githubusercontent.com/15233243/100524744-750f4d00-316f-11eb-83de-8599a846c550.gif)
