### ISSUE TITLE
Add an interaction to keep questions on view

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#211]
## Problem
During tests, we identified that users with smaller screens can lose the next question when selecting answers on the left side. Especially in the attribution question. We have not tested on mobile resolutions but we are aware that it requires scrolling down to see the next question.

## Description
We need to add an interaction that keeps the current question on view. Both desktop and mobile. For *finishing the process* I will update the mockups but it needs to be considered a `done` button since the "Recommended license" is crucial to indicate that the process ended.

I envision an interaction where there is no animation but an instant jump that puts the next question on top of the page.

**Comment by obulat** [comment]
This issue has been solved in #253.
