### ISSUE TITLE
Implement the mockups for release v2

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#212]
## Description
After the round of 12 test. We identified different issues with regard to interaction, content, and value proposition of the Chooser. For this v2 update, [the mockups](https://www.figma.com/file/NnTin7MBlEuG2Hxb6T94ZH/Mockup---2nd-release?node-id=91%3A0&viewport=163%2C217%2C0.051361385732889175) have been updated based on Vocabulary. The main changes are:
1. **Components update based on Vocabulary components:** Buttons, inputs, text styles, and spacings have been updated based on the Design Library documentation.
2. **Content improvement:** Titles, descriptions, and questions have changed to be more clear and specific about their intentions.
3. **Interaction improvements:** Auto-scroll, `start again`, and a toggle for license name's length have been added to improve the experience.
4. **New content structure for Recommended License:** This content structure changed following the License redesign to keep consistency when seeing the license detail.

## Screenshot
<img width="841" alt="Screen Shot 2020-11-20 at 13 31 10" src="https://user-images.githubusercontent.com/895819/99824603-af0b9e00-2b34-11eb-94d5-ec13cab64900.png">

## Additional context
This new version must include the tickets associated with bugs and the most important changes were indicated in the following tickets:
- #213 
- #214 
- #215 
- #216 
- #217 
- #218 
- #219 
- #220

**Comment by panchovm** [comment]
This ticket was updated by linking all tickets created for content and design changes.

**Comment by obulat** [comment]
All the sub-issues of this meta issue have been solved.
