### ISSUE TITLE
Move the FAQ to the end of left section

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#216]
## Description
Based on the mockups (2nd release), we need to move the FAQ section below the questions on the left. The behavior should be the same as current, display the answer in a modal.

<img width="463" alt="Screen Shot 2020-11-23 at 16 18 29" src="https://user-images.githubusercontent.com/895819/100005329-88a16900-2da7-11eb-90b5-bc6c93e91d68.png">

**Comment by Aspie96** [comment]
On desktop there is more than enough space on the right side.

I suggest it actually looks better as is. On mobile the FAQ are to the bottom already.
