### ISSUE TITLE
Actions to finish and start again the process

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#218]
## Description
Based on the [mockups (2nd release)](https://www.figma.com/file/NnTin7MBlEuG2Hxb6T94ZH/Mockup---2nd-release?node-id=91%3A0&viewport=-8998%2C-180%2C0.8576911687850952), we need to include two actions in the final question on left:
- **Done:** Applies a slightly shake effect on the **Mark your work** section
- **(*) Start again:** Start the process from Question 1

<img width="590" alt="Screen Shot 2020-11-23 at 16 29 39" src="https://user-images.githubusercontent.com/895819/100006336-192c7900-2da9-11eb-94ca-7efe9ae3ce23.png">

As discussed during the hand-off meeting, it would add value to the experience if we keep the responses/data if user selects the same responses. This is not critical for the experience, therefore, it's a low priority.

**Comment by obulat** [comment]
This issue has been solved in #253.
