### ISSUE TITLE
CC0 image error

### ISSUE THREAD

**Issue by kgodey** [creativecommons/chooser#249]
Reported via email:

> Me and my students are very pleased to use your chooser-beta.creativecommons.org site to create proper refernces on CC materials.
>  
> We have noticed that when creating the CC0 refernce for HTML pages, there is a mistake in a code where the link to the 0 image isnt's correct.
>  
> For better understanding:
> 
> ![m00ylTjG_yKQHI7RGx3CdG36XA0EsxzpuQ](https://user-images.githubusercontent.com/287034/101810190-7aad5100-3ae6-11eb-8e81-aa1bdf00ae07.jpg)
>

**Comment by neeraj-is-coding** [comment]
Can I take it?

**Comment by neeraj-2** [comment]
@kgodey ,Can I work on it?

**Comment by obulat** [comment]
Thank you for reporting this issue, it is VERY important.  I've fixed this in [#195](https://github.com/creativecommons/chooser/pull/195), and it will go live when we deploy the latest version of the Chooser. So this issue can be closed.
