### ISSUE TITLE
Color in number indicator within step box

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#255]
## Description
The step number in the top-left corner of the box is using an incorrect green color. It should be the `$color-forest-green`

## Screenshots
<img width="222" alt="Screen Shot 2020-12-16 at 11 02 45" src="https://user-images.githubusercontent.com/895819/102358415-3dd1d600-3f8e-11eb-86ec-919819a1685f.png">

**Comment by neeraj-2** [comment]
@panchovm, can I take it?

**Comment by obulat** [comment]
> @panchovm, can I take it?

Sure, go ahead! The vocabulary variables are not imported in the Chooser yet, so you will have to use the color value itself. Here is the code for the color:
https://github.com/creativecommons/chooser/blob/aedf03bb3e2fcffc77c9597de5beff992f662068/src/components/StepHeader.vue#L109

**Comment by neeraj-2** [comment]
> > @panchovm, can I take it?
> 
> Sure, go ahead! The vocabulary variables are not imported in the Chooser yet, so you will have to use the color value itself. Here is the code for the color:
> https://github.com/creativecommons/chooser/blob/aedf03bb3e2fcffc77c9597de5beff992f662068/src/components/StepHeader.vue#L109

Thanks, @obulat :)
