### ISSUE TITLE
Hover style of default links

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#256]
## Description
The default links change from tomato to black, plus an underline, during hover state. The color should not change, only adding the underline style.

## Screenshots
<img width="343" alt="Screen Shot 2020-12-16 at 11 08 46" src="https://user-images.githubusercontent.com/895819/102359067-162f3d80-3f8f-11eb-9a0d-cb8b73de4012.png">

**Comment by neeraj-2** [comment]
I would like to work on it. Can I?
