### ISSUE TITLE
Text color in descriptions

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#257]
## Description
The chooser description, below the main title, and the license description are using a different color for the default text. It should be the `$color-dark-slate-gray` for all body content across all the site.

## Screenshots
<img width="666" alt="Screen Shot 2020-12-16 at 11 09 31" src="https://user-images.githubusercontent.com/895819/102359651-d1f06d00-3f8f-11eb-8111-583b81cd5ecc.png">

**Comment by rohan-goel** [comment]
Hey, I would like to work on this issue.

**Comment by obulat** [comment]
@panchovm , the color in the Figma design is black... It should still be $color-dark-slate-gray?

**Comment by panchovm** [comment]
Oh! You are right. That is my mistake. And yes, it should be $color-dark-slate-gray. Although my understanding is that icons are black, if it so, then icons should keep being black.

**Comment by obulat** [comment]
So, license icons should be black, and the text $color-dark-slate-gray? (#333333)

**Comment by panchovm** [comment]
Yes 👍
