### ISSUE TITLE
Content repeated in the NC description

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#258]
## Description
In the license definition section, the NC has repeated the Noncommercial meaning.

## Screenshots
<img width="621" alt="Screen Shot 2020-12-16 at 11 19 26" src="https://user-images.githubusercontent.com/895819/102360395-b8035a00-3f90-11eb-8ed2-6b5369f7b641.png">

**Comment by rohan-goel** [comment]
Hey, I would like to work on this issue.

**Comment by rohan-goel** [comment]
I'm unable to replicate this issue, how should I replicate it ??

**Comment by obulat** [comment]
@rohan-goel , the problem is here: 
https://github.com/creativecommons/chooser/blob/94bd9253e79ec7a8563fca45b628c84243ad2400/src/components/LicenseDetailsCard.vue#L37
You might not be able to replicate it if your Chooser fork is not up-to-date. This regression was introduced recently.
