### ISSUE TITLE
Defult size of text area in Waive Your Copyright question

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#260]
## Description
The height of textarea component in Waive Your Copyright question looks too small. I suggest setting a default height of `270px` in order to make it more visible.

## Screenshots
<img width="576" alt="Screen Shot 2020-12-16 at 11 42 35" src="https://user-images.githubusercontent.com/895819/102364419-2ea25680-3f95-11eb-998d-c3658645f4b4.png">

**Comment by rohan-goel** [comment]
Hey, I would like to work on this issue.

**Comment by obulat** [comment]
This issue was solved in #253.
