### ISSUE TITLE
Y position of question box

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#261]
## Description
**Resolution: Mobile**
After answering a question, the Y position of the following box does not fit the display view.

## Screenshots
<img width="334" alt="Screen Shot 2020-12-16 at 12 24 46" src="https://user-images.githubusercontent.com/895819/102368858-197bf680-3f9a-11eb-9a52-590b1abc0c8d.png">

**Comment by obulat** [comment]
This issue was solved in #253.
