### ISSUE TITLE
Text style and alignment in radio component

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#262]
## Problem
Viewing the site on a mobile device, the radio component might improve the following issues:
1. Font-size of radio component is too small in comparison to the question's font-size. We might try the `body-normal` style.
2. The spacing between title and radio looks too big. We might try `16px` instead of `24px`

## Screenshot
<img width="294" alt="Screen Shot 2020-12-16 at 12 35 35" src="https://user-images.githubusercontent.com/895819/102370171-8b087480-3f9b-11eb-997f-0525e05739f9.png">

**Comment by rohan-goel** [comment]
Hey, I would like to work on this issue.

**Comment by obulat** [comment]
Sure, @rohan-goel , go ahead!

**Comment by obulat** [comment]
Closed by #277
