### ISSUE TITLE
The attribution text is copied wrongly on mobile

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#264]
## Description
When copying the attribution text on mobile, it copies the following text structure:

## Screenshots
![IMG_8041](https://user-images.githubusercontent.com/895819/102389350-c01fc180-3fb1-11eb-9f71-51ca6c1b55bd.jpg)
![IMG_8042](https://user-images.githubusercontent.com/895819/102389351-c150ee80-3fb1-11eb-90dd-3200bfffbcc4.jpg)

**Comment by obulat** [comment]
This definitely looks weird. Could you tell me what phone you are using and which link do you use to preview?  I tried on my phone, and it works fine, although the license icons are pasted only to MS Word, not Google docs.

**Comment by panchovm** [comment]
I am on firefox, iPhone 6S, and pasted on Bear app.

**Comment by Cronus1007** [comment]
![Screenshot from 2020-12-22 20-21-27](https://user-images.githubusercontent.com/56436023/102901193-56148a00-4493-11eb-8ec2-f111f1e427c8.png)
![Screenshot from 2020-12-22 20-22-53](https://user-images.githubusercontent.com/56436023/102901351-83f9ce80-4493-11eb-8b51-d7a829421c39.png)
@panchovm  Everything is working fine.

**Comment by panchovm** [comment]
I think it was an issue with the app I was using. Closing this issue.
