### ISSUE TITLE
Text style in line tab component

### ISSUE THREAD

**Issue by panchovm** [creativecommons/chooser#265]
## Problem
Based on the mockup, the line tab component in the **Mark your work** section changes to a select. The current implementation looks better than the mockup, but I recommend using the `Heading 6B` style for the labels.

## Screenshot
<img width="353" alt="Screen Shot 2020-12-16 at 15 31 37" src="https://user-images.githubusercontent.com/895819/102390932-cdd64680-3fb3-11eb-8d4c-62f1a46d34f7.png">

**Comment by ryuk156** [comment]
Can i work on this?

**Comment by Cronus1007** [comment]
@ryuk156 I am already working on this issue.

**Comment by ryuk156** [comment]
No problem  @Cronus1007 go ahead 👍

**Comment by akshayprabhu200** [comment]
Is this issue open?

**Comment by Cronus1007** [comment]
@akshayprabhu200  By EOD I am going to send the PR fixing the issue soon.
