### ISSUE TITLE
Document JavaScript coding guidelines

### ISSUE THREAD

**Issue by Cronus1007** [creativecommons/chooser#278]
### Issue Description 
I intend to write guidelines and base configuration files for working with JavaScript in Creative Commons projects. This will include:

- Best practices
- Prettier configuration
- Eslint configuration
- JSON formatting
- Vue standards

This will most likely live on the open source site, and perhaps the wiki. We don't have existing language guides so this would possibly be the first and set some precedents for other guides. In that aim I'd like to follow some certain language conventions:

Avoiding language like "simply|just|easy" see: https://jameshfisher.com/2017/02/22/dont-use-simply/
Consider items in the Mozilla Writing Style Guide: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide
Take guidance in structure from Firefox JS Guidelines: https://firefox-source-docs.mozilla.org/code-quality/coding-style/coding_style_js.html

@obulat  We can refer issue https://github.com/creativecommons/creativecommons.github.io-source/issues/509 from @zackkrida  Since it will make both the review and code committing easier

**Comment by Cronus1007** [comment]
@obulat  i would like to work on this issue as well

**Comment by bryanlaura736** [comment]
Please do!!

**Comment by obulat** [comment]
@Cronus1007 The Javascript guidelines should be written centrally, for all of the Creative Commons repositories, and then applied everywhere. Chooser repo is not a place for separate guidelines, so I am closing this issue here. Work on the coding guidelines should continue in another repo.

**Comment by Cronus1007** [comment]
@obulat  I want to edit this file since `editorconfig` lacks a lot and missing config for  `js` speciffically and then it is upto the editor how it will lint our files and errors may occur. So for the best practice we should edit our `editorconfig` and shall reopen this issue.

**Comment by obulat** [comment]
@Cronus1007 In order to not do the same things twice, it is best to add `editorconfig` here AFTER it has been agreed on in Vocabulary, so the coding style is the same across all JS repos.
