### ISSUE TITLE
Large bundle size

### ISSUE THREAD

**Issue by obulat** [creativecommons/chooser#279]
## Description

Currently, the Chooser's bundle size is quite large for a single page. 

## Reproduction

1. Run `npm run build` in the Chooser, or generate Lighthouse report in Google Chrome.
2. See problem.

These are webpack build warnings:
```
  File                                Size          Gzipped
  dist\js\chunk-vendors.59d80c80.js   695.35 KiB    200.24 KiB
  dist\js\app.02a91d51.js             107.03 KiB     34.23 KiB
  dist\css\app.79796147.css           218.88 KiB     32.01 KiB
```

And here is a part of the Lighthouse report:
![image](https://user-images.githubusercontent.com/15233243/103649612-994f0e00-4f13-11eb-8784-dc88776539d1.png)

## Possible steps to take:

-  Remove some third-party libraries, or replace them with lighter versions.  Some of the libraries we should consider are:

- [x]  `sentry`
- [x]  `buefy`
- [ ] `markdown-it`

- [x] Purge unused CSS using `purge-css` library.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by koolgax99** [comment]
can you please assign me this issue @obulat

**Comment by obulat** [comment]
Sorry, @koolgax99 , I am already working on this.

**Comment by koolgax99** [comment]
Okay @obulat. Can you assign me some issues and help me in understanding the codebase?
