### ISSUE TITLE
CD is failing due to authorization issue

### ISSUE THREAD

**Issue by obulat** [creativecommons/chooser#284]
## Description

Chooser repo has github actions configured to deploy the site on push to the `master` branch. However, it is failing because I am not authorized to push into the master branch without an approved review. 

## Reproduction

1. Merge a change into the master branch.
2. Review the logs from github 'Publish' action
3. See error.

## Expectation

The site should be published to github pages at  `https://chooser-beta.creativecommons.com`

## Screenshots

```bash
  Tagging commit...
  Pushing commits to repo...
  remote: error: GH006: Protected branch update failed for refs/heads/master.        
  remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.        
  To https://github.com/creativecommons/chooser
   ! [remote rejected] master -> master (protected branch hook declined)
  error: failed to push some refs to 'https://github.com/creativecommons/chooser'
  Pushing tags to repo...
  remote: error: GH006: Protected branch update failed for refs/heads/master.        
  remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.        
  To https://github.com/creativecommons/chooser
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/creativecommons/chooser'
Task completed.
```

## Additional information
Now that we've updated the `npm run build` command to build and copy the necessary files to the `docs` folder, we can remove the following steps from the workflow file:
```bash
                  echo "chooser-beta.creativecommons.org" > "./dist/CNAME"
                  rm -r -f "./docs"
                  mv -f -v "./dist" "./docs"
```

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
@obulat The best way to deal with this would to have a more formal release process, something like the following:

- For every deployment, make a Pull Request into master. 
- This PR will bump the version number in `package.json` and in the `package-lock.json` (can use the command `npm version [major | minor | patch]` for this, which will also automatically create a git tag and commit)
