### ISSUE TITLE
"This work marked"

### ISSUE THREAD

**Issue by Aspie96** [creativecommons/chooser#288]
## Description
When a work is marked under CC0 it should say: "this work IS marked under CC0". The verb is missing

## Reproduction

1. Generate a CC0 license waive2
2. It will say "this work marked under" with no "is".

## Expectation
It should make grammatical sense.

## Resolution
- [ ] I would be interested in resolving this bug.

**Comment by obulat** [comment]
Thank you for your report, @Aspie96 , great catch!

**Comment by neeraj-2** [comment]
Can I work on it?

**Comment by obulat** [comment]
Sure, go ahead, @neeraj-2! You would need to edit the `locales\en.js` file, specifically the `marked-text` field.

**Comment by Aspie96** [comment]
Question!

Should it be, instead, "this work is marked WITH CC0"? The word "with" makes more sense with "marked" to me.

**Comment by obulat** [comment]
That's correct, it should be "this work **is** marked **with** CC0". Actually, the current version already says 'with', so we only need to add 'is'.

**Comment by Aspie96** [comment]
Apologize, I misread it.

**Comment by obulat** [comment]
No problem! Thank you for reviewing the copy, @Aspie96 !

**Comment by neeraj-2** [comment]
Hey @obulat and @Aspie96. I noticed something. I think the typo is in the deployed version only. When I run the project locally , it is errorless. I have attached the screenshot of the same here.



![image](https://user-images.githubusercontent.com/56186425/104096105-7bd9c580-52c0-11eb-9ae6-589b39a5fb7d.png)

**Comment by obulat** [comment]
@neeraj-2 , I notice that your repo is quite behind upstream. This error was probably introduced recently. Could you update your branch and fix the error?

**Comment by neeraj-2** [comment]
Oh. Thanks, @obulat for pointing it out. I will update it and will create a PR

> @neeraj-2 , I notice that your repo is quite behind upstream. This error was probably introduced recently. Could you update your branch and fix the error?
