### ISSUE TITLE
Double "rel" attribute

### ISSUE THREAD

**Issue by Aspie96** [creativecommons/chooser#292]
## Description
The code currently generated by the license chooser contains the following tag:
`<a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">`

The first "rel" attribute should be removed.

## Resolution
- [ ] I would be interested in resolving this bug.

**Comment by obulat** [comment]
Thank you for reporting this issue, @Aspie96 !

**Comment by neeraj-2** [comment]
I would like to work on this issue. Can I?

**Comment by Aspie96** [comment]
I could be wrong but for issues this small, @neeraj-2, I would probably just file a PR without asking first.
Asking makes sense for complex tasks to avoid duplication of effort.

**Comment by obulat** [comment]
Sure, @neeraj-2 , please go ahead
