### ISSUE TITLE
Make link to work always an absolute URL

### ISSUE THREAD

**Issue by obulat** [creativecommons/chooser#296]
## Description

When a user fills in the Attribution Details form, 'Mark your work' section is automatically updated. The URL from 'Link to Work' field is used as the URL for `href` attribute for the `<a>` anchor tag that includes the link to work in the RichText and HTML boxes. 

Currently, if a user provides a URL without the leading `http`, the `workUrl` computed prop adds `http://` to the start of URL to make it absolute. However, due to the bug, the result of this computed prop is not used, and instead, the URL becomes relative, not absolute.

## Reproduction

1. Select any license and go through the step to get to the last step, Attribution Details form.
2. Enter a URL without the leading `http`, i.e. `www.example.com/picture.jpg`
3. Look at the Richtext box in the 'Mark your work' section.
4. See error: the link in the attribution text becomes `https://chooser-beta.creativecommons.org/www.example.com/picture.jpg`.

![image](https://user-images.githubusercontent.com/15233243/104121077-90ce4d00-52f0-11eb-9617-9c3c56d3ccd7.png)

## Expectation

The `href` attribute should be absolute, i.e. `http://www.example.com/picture.jpg` in the example.

## Additional context

Here is the line that needs to be changed:
https://github.com/creativecommons/chooser/blob/404fea77f103cf36fe54e8a3607eaf5ad0e8e1cf/src/components/LicenseText.vue#L120

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by neeraj-2** [comment]
I would like to work on it. Can I?

**Comment by obulat** [comment]
Sure, go ahead, @neeraj-2 !
