### ISSUE TITLE
Link to work not displayed in HTML attribution code if no work title provided

### ISSUE THREAD

**Issue by obulat** [creativecommons/chooser#297]
## Description

When the user provides a link to work, but does not provide a title, HTML attribution code in the 'MARK YOUR WORK' should add a link with `href` of the user-provided link, and text of 'This work'. Because there is no title, there should not be the `property="dct:title"` attribute:

```<a rel="cc:attributionURL"  href="http://www.example.com/picture.jpg">This work</a> ```

Instead, now no link is added even if the user provides a URL to their work:
```This work ```

## Reproduction

1. Select any license and get to the last step, Attribution details form.
2. Fill in only the 'Link to work' field with a URL.
3. Select 'HTML' tab in the 'MARK YOUR WORK' section.
4. See error: The code has only `This work `

## Expectation

HTML code should have  `<a rel="cc:attributionURL"  href="http://www.example.com/picture.jpg">This work</a> ` in it.

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by rohan-goel** [comment]
Can I work on this issue?

**Comment by obulat** [comment]
Sure, @rohan-goel , go ahead!
