### ISSUE TITLE
Update @vue/test-utils

### ISSUE THREAD

**Issue by obulat** [creativecommons/chooser#301]
## Problem

Chooser uses `@vue/test-utils` for unit testing. The version used is 1.0.0-beta.29. We need to update it to the most recent version, 1.1.2.

## Description

In addition to changing the package, we need to address breaking changes:

1. delete `isVueInstance` assertions
2. remove all checks that use `wrapper.name`.
3. replace checks with `wrapper.contains` with `wrapper.find().exists()).toBe(true)`
4. ensure that changes to props/vuex/events caused by calling `trigger` have been processed by Vue by making the test function using those async, and awaiting on the following functions:
  - `wrapper.setProps`
  - `trigger('click')` and similar trigger functions.
  - `state.commit` and similar Vuex changes

## Additional context

Currently, the only test that we have for `App.vue` component is `isVueInstance`, so we can delete that file, and create a test for `App.vue` in a separate PR.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by Cronus1007** [comment]
@obulat let me take over this issue.

**Comment by obulat** [comment]
Sure, @Cronus1007, go ahead!
