### ISSUE TITLE
Create Cypress integration test for Stepper

### ISSUE THREAD

**Issue by obulat** [creativecommons/chooser#302]
## Problem

We need to have e2e tests for testing user interaction with the Chooser. Currently, we are using Selenium-based Nightwatch. However, after we added auto-scrolling, Stepper tests often fail because Nightwatch cannot find an element that is probably off-screen at the moment of testing. 

## Description

We want to add a Cypress test spec for the Stepper instead of the Nightwatch spec.
In `cypress/integration/stepper_spec.js` we should test the following:

1. The user can select a license using the dropdown. After a 'yes' answer to the first question ('I know which license I need'), the stepper should have three steps. Here, we need to test two scenarios:

- [ ] The user selects CC0 in the dropdown. After selection, '.recommended-card' should be visible. To check the selected license, we can use the license displayed in the `.recommended-card`.  When the user clicks next, the Copyright Waiver should open, and the total number of steps should be 4. When the user checks the two checkboxes, the Attribution details step and the `.license-use-card` should open.

- [ ] The user selects a CC BY-NC-ND license in the dropdown. After the user clicks 'Next', the Attribution details step opens (i.e., there is no Copyright Waiver step, only 3 steps total)

2. The user can select licenses using the steps, i.e. after clicking 'No, I need help' on the first step.

- [ ] The user can select CC0 using the steps. When the user clicks on 'No' answer in the 'BY' question, the `.recommended-card` should appear. In this case, the three following steps (NC, ND, SA) should be disabled. Then, the user can click waiver checks, and then open the Attribution details step.

- [ ] The user can select 'CC BY' using steps: 'Yes' on the first step. When the user clicks on 'Yes' answer in the 'BY' question, the `.recommended-card` should appear.  Then the user selects the necessary choices for the 'CC BY' license, and open the Attribution details step in the end. When the Attribution details step opens, the `.license-use-card` should appear.

- [ ] The same test for choosing 'CC BY-NC-ND' license. In this case, however, the SA step should be disabled.

4. The user should be able to go back using the 'Back' button:

- [ ] From the Attribution details, after selecting 'CC BY-ND' using steps. The user can click 'Back' to get to the step Number 4, change the selection to 'Yes' on this step, and select 'No' on 'SA' step and go forward to the Attribution Details. In this case, the selected license should be 'CC BY-SA'
- [ ] After selecting 'CC0' using the license dropdown and getting to the 'Attribution Details' step, the user can go back to the first question, select 'No' on the first question, and then follow the steps to select 'CC BY-NC-SA' license.

5. The user should be able to start over using the 'Start again' button on the last step.
6. The user should see the window scroll to the 'Mark your license' section after clicking on 'Done'

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by Cronus1007** [comment]
@obulat I definately want to go for this issue as well. So when I am finished with #301 then I will go for it.Until then assign it to me

**Comment by obulat** [comment]
Sure, @Cronus1007 , I am waiting for your PRs.

**Comment by Cronus1007** [comment]
> 2. The user can select CC0 using the steps. In this case, the three following steps should be disabled. Then, the user can click waiver checks.
> 3. The user can select the following licenses: 'CC BY',  'CC BY-NC-ND' (in this case, SA step should be disabled).
Plzzz give an extra explanation regarding these two points.

**Comment by obulat** [comment]
> > 1. The user can select CC0 using the steps. In this case, the three following steps should be disabled. Then, the user can click waiver checks.
> > 2. The user can select the following licenses: 'CC BY',  'CC BY-NC-ND' (in this case, SA step should be disabled).
> 
> Plzzz give an extra explanation regarding these two points.

For point 1, the flow is:
The user selects No (I need help selecting the license) in the first step.
In the second step, the user selects "No" to attribution, therefore selecting CC0. 
When the user then clicks "Next", the next open step should be Copyright waiver. There, the user can check the waiver checkboxes and go to Attribution Details step.

**Comment by Cronus1007** [comment]
@obulat Yup in #305 everything is sorted now since https://github.com/creativecommons/chooser/tree/master/tests/e2e/specs
I have rewritten all of this code into Cypress.
