### ISSUE TITLE
Add step to determine appropriateness of CC licenses

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/chooser#314]
## Description

Users who aren't familiar with Creative Commons licenses might not know if the licenses are actually appropriate for their work and use case. We would like to add a step to the chooser that lets the user confirm a CC license is the right fit.

This issue will be updated with the exact copy, but in the meantime a **draft pull request** may be created that adds a 'generic' new second step to the chooser flow, that can be filled in with the appropriate content when ready.

**Comment by neeraj-2** [comment]
I would like to work on it. Can I?

**Comment by zackkrida** [comment]
Sure @neeraj-2! Thanks.

**Comment by zackkrida** [comment]
Hey @neeraj-2 will you be actively working on this this week? Just curious. Thank you!

**Comment by neeraj-2** [comment]
> Hey @neeraj-2 will you be actively working on this this week? Just curious. Thank you!

Yes, @zackkrida. I am actively working on this one right now. (What I did in last some days) was just doing some background research to have a start on this issue. Explored the  7 CC licenses and their details and looking at our chooser website to get through what details already exist and what I should add-in. And now want your guidance so that I can understand from where I should exactly start 😊.

**Comment by neeraj-2** [comment]
Should I propose some interface on figma? Or something like that to have a start with this issue?

**Comment by zackkrida** [comment]
It shouldn't require any design work; we need a new step added to the stepper (a new step 2) so the current step 2 becomes step 3. If they choose "no, i need help" it will go to the new step, otherwise it will still skip multiple steps the same way it currently works.

You can just use lorem ipsum / placeholder text for the new step.

<img width="512" alt="2021-02-08-137" src="https://user-images.githubusercontent.com/6351754/107267124-8d5edc00-69ea-11eb-975e-5006969ff907.png">

**Comment by neeraj-2** [comment]
Thanks, @zackkrida for the details. I Will create a Draft PR soon.

**Comment by obulat** [comment]
Will this step have radio inputs, just like the first step? If so, we could add another step object to the list of step objects, and use the ChooserStep component for it.

**Comment by neeraj-2** [comment]
Have just created a draft PR. But some work is still required. So, I am on it and will try to complete it by this week
