### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by obulat** [creativecommons/chooser#317]
## Problem

As discussed in #312, we can add some improvements to the general code organization and code quality, as well as bringing the Chooser code in line with the other CC code. Some of the necessary changes can be copied from the code in #312.

1. Change the indent size from 4 to 2 spaces.
2. Add prettier and stylelint.
3. Add a pre-commit check to ensure that all committed code is free of linting errors. `vue-cli` already has `yorkie`, a fork package of `husky`, installed to add the pre-commit hooks. Here is the link to the documentation: https://cli.vuejs.org/guide/cli-service.html#git-hooks . 
We need to add `lint-staged` pre-commit hook that will run the lint command from `package.json`.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by rohan-goel** [comment]
Hey @obulat , I would like to work on this issue.

**Comment by Cronus1007** [comment]
@obulat For adding `lint-staged` the first priority is going to implement the prettier configs in the form of `.prettierrc`. And then while calling the `lint-staged` pre-commit hook then call the `prettier --config (file referred) --write`.

**Comment by obulat** [comment]
> @obulat For adding `lint-staged` the first priority is going to implement the prettier configs in the form of `.prettierrc`. And then while calling the `lint-staged` pre-commit hook then call the `prettier --config (file referred) --write` or are you preferring only `eslint` configs for linting.

I have updated the issue text to add more necessary changes.

**Comment by obulat** [comment]
@rohan-goel , I have updated the issue with more changes. If you are OK with them, please, go ahead and implement them!

**Comment by rohan-goel** [comment]
Sure, working on it.
