### ISSUE TITLE
Add integration test for Mark Your Work section and its interaction with Stepper and Attribution Details Step

### ISSUE THREAD

**Issue by obulat** [creativecommons/chooser#318]
## Problem

'Mark Your Work' section shows the license code for attribution purposes, in rich text, plain text, or HTML format.  It is updated automatically any time the license or attribution information (Creator name, etc.) is changed. The interaction of the 'Mark Your Work' section needs to be tested using Cypress tests.

## Description
This is the list of scenarios that need to be tested:
### Mark Your Work section appears and is hidden at the correct moments
- The 'Mark Your Work' section should be invisible at the beginning
- It should appear when the user selects a license from the dropdown and clicks Next
- It should disappear when the user clicks Back.
- When the user clicks back again, and then uses the steps (i.e. clicking I need help on the first step) to choose the license, the 'Mark Your Work' section should appear again when the last step is selected.

#### Mark Your Work section correctly shows the license in the correct format:
- When the user selects 'CC BY', the license is shown correctly in all tabs
- When the user changes attribution type, the license changes from Short to Full, accordingly

#### Attribution details are updated correctly:
- When the user adds information in the attribution details, the license code is updated accordingly

#### The license code can be copied to the clipboard:
- When the user clicks on 'Copy', the button text changes to 'Copied', and the clipboard contains the license text.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by Cronus1007** [comment]
@obulat I would like to implement this issue.

**Comment by obulat** [comment]
Sure, @Cronus1007 , go ahead!

**Comment by Cronus1007** [comment]
> When the user changes attribution type, the license changes from Short to Full, accordingly

@obulat Enhance this point of yours.Unable to predict anything from this. Does it mean CC By converts into CC0

**Comment by zackkrida** [comment]
@Cronus1007 Olga is talking about testing this toggle: 

<img width="464" alt="2021-02-19-149" src="https://user-images.githubusercontent.com/6351754/108564998-14903780-72a8-11eb-863b-b06054520cb2.png">
<img width="457" alt="2021-02-19-148" src="https://user-images.githubusercontent.com/6351754/108565006-1823be80-72a8-11eb-866e-05baad1ebbe7.png">

**Comment by Cronus1007** [comment]
@zackkrida One more doubt related to the Attribution Steps.What to type in `Link of Work` and `Link to Creator Profile`. Also I have to check working of these links.
![Screenshot from 2021-02-20 09-25-16](https://user-images.githubusercontent.com/56436023/108583136-92fae100-735d-11eb-87eb-48cab0a535d8.png)

**Comment by zackkrida** [comment]
@Cronus1007 good questions. you don't need to test if the links work, or even if they're valid urls, those are implementation details best left to the user. 

You can use https://creativecommons.org as the url for both in your tests.
