### ISSUE TITLE
Add new "year of creation" attribution detail

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/chooser#325]
## Description

From Sarah in legal:

> In Attribution Details for the licenses (but not CC0), add “Year of Creation” which should manifest in the attribution text as © 2021 after the Title and before the Creator Name.

**Comment by Cronus1007** [comment]
@zackkrida I would like to implement this issue.

**Comment by Cronus1007** [comment]
@zackkrida Let me generate a draft PR now for this. So that you can have a look at the progress.
