### ISSUE TITLE
Feature: Add more context to Creator Name

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/chooser#326]
## Description

Add the following text near the `Creator Name` field: 

> In addition to the creator of the work, include here any others who should receive attribution. For example, if you created a work on behalf of your employer who owns copyright in the work, you may want to include your employer’s name as one of the attribution parties.

## Alternatives

We should figure out how to best add this copy without cluttering the UI too much. Should it be in an info ℹ️ popup/tooltip, a modal, or right inline with the copy? I'm open to suggestions from whoever implements the issue.

**Comment by Cronus1007** [comment]
@zackkrida I would like to work upon this issue.

**Comment by zackkrida** [comment]
Great thanks

**Comment by Cronus1007** [comment]
@zackkrida For this what we can do is above the `AD` step we can waive a `checkbox ` for this and if someone checks it then a new field may appear in the `AD` .

**Comment by obulat** [comment]
I would vote for popup/tooltip for this feature. And in the future, if we decide to add context to other steps, we would also use the same popup/tooltip.

**Comment by zackkrida** [comment]
@Cronus1007 I agree with Olga. For _now_, you could use the existing modal (from when you click on a CONFUSED? NEED HELP? link, for example) that is opened when the user clicks on the info icon (see here: https://cc-vocabulary.netlify.app/?path=/docs/tokens-icons--figma) next to the "Creator Name" field.
