### ISSUE TITLE
unnecessary <p> tag in Modals.

### ISSUE THREAD

**Issue by Cronus1007** [creativecommons/chooser#340]
## Description

The modal text of `What do the Icons Mean` has un necessary `<p>` tag which should not be present as the text says 
`<p>The icons represent key features of the different CC license options:</p>`
rather than `The icons represent key features of the different CC license options`
## Reproduction

1. npm  run serve
2. Click upon `What do the Icons Mean`.
3. See the Modal. The modal is also linked down below. 
4. See Error

## Screenshots
![Screenshot from 2021-03-05 21-00-23](https://user-images.githubusercontent.com/56436023/110136940-4bad2f80-7df6-11eb-87d5-3ed6c9eab77d.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Great catch @Cronus1007, I was just about to make an issue for this. Please go ahead and fix it.
