### ISSUE TITLE
Fix step order

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/chooser#345]
## Description

At some point, i incorrectly moved the "Confirm that CC licensing is appropriate" order to the _second_ step—it should be second to last. Please keep in mind that e2e test instructions will need to be adjusted.

**Comment by zackkrida** [comment]
@neeraj-2 Please!

**Comment by neeraj-2** [comment]
@zackkrida If I am not wrong we want the "Confirm that CC licensing is appropriate" step after the "Attribution Details" step, right??

**Comment by sarahpearson** [comment]
@neeraj-2 Good question. I think in order to match what we do for CC0, that confirmation step should go *before* Attribution Details but after the other steps of choosing a license.
