### ISSUE TITLE
Upgrade project to Vue 3

### ISSUE THREAD

**Issue by brylie** [creativecommons/chooser#360]
Vue 3.0 was [released in September 2020](https://github.com/vuejs/vue-next/releases/tag/v3.0.0). However, this project is still using Vue 2.x.

Decide when it is time to upgrade this project to Vue 3.x

## Description
One of the design constraints of Vue 3.x was to preserve backward compatibility with Vue 2.x projects. This would ideally mean very little would need to change when the Chooser project upgrades to Vue 3.x.

## Alternatives
We can stay at 2. x, but that would mean decreasing support as 2.x reaches end-of-life. 

## Additional context

The upcoming Vue 3.1 release includes a "[Migration Build" to help projects transition from 2.x to 3.x](https://github.com/vuejs/vue-next/tree/master/packages/vue-compat).

The Vue User Guide is defaulting to 3. x to signal that projects should be targeting the 3. x release.

:warning: Vue 3. x drops support for IE 11

**Comment by Cronus1007** [comment]
@brylie Would love to be a part of the transition from Vue 2.0 to Vue 3.0.

**Comment by brylie** [comment]
@Cronus1007, would you mind if I assign you to this issue? If you would like to give it a try, go ahead and create a pull request with your Vue 3 changes, even if they are in draft form. That way, we can discuss and test the changes collaboratively.

**Comment by brylie** [comment]
My bad. I opened a duplicate issue of #356 in this repository. My intention was to open the issue in the CC Vocabulary project, which I have now done. I'm closing this issue as a duplicate.

@Cronus1007 would you be interested in helping with the CC Vocabulary Vue 3 migration?

**Comment by Cronus1007** [comment]
@brylie  Sure
