### ISSUE TITLE
Remove Hotjar-related packages and code

### ISSUE THREAD

**Issue by brylie** [creativecommons/chooser#372]
We currently include two packages related to Hotjar in `package.json` and some analytics code throughout our components. However, the Hotjar code may no longer be necessary since we are not actively using Hotjar analytics for any internal measurements.

## Task

- [ ] remove Hotjar/analytics code from Vue components
- [ ] remove Hotjar packages from `package.json` including `vue-analytics`

**Comment by clasick** [comment]
@brylie Thanks for the clarification!

> @clasick you can work on this, now that the confusion has been cleared! 😃 

Yup, I've started on a fix for this. ✌️

**Comment by brylie** [comment]
When running `npm install`, I see the following warning:

> vue-analytics@5.22.1: Sorry but vue-analytics is no longer maintained. I would suggest you switch to vue-gtag, with love, the guy who made the package.

I think we should just remove the analytics code entirely, and not use `vue-gtag` as suggested. Just adding a note here.

**Comment by brylie** [comment]
@clasick, any update on this task?

**Comment by yaya-usman** [comment]
@brylie Hi, i think i should  give this a try, can i get assigned this?

**Comment by brylie** [comment]
Sure thing, @yaya-usman. I'll assign you.

**Comment by yaya-usman** [comment]
> Sure thing, @yaya-usman. I'll assign you.

Thanks

**Comment by MuluhGodson** [comment]
Good Housekeeping
Closed by #391
