### ISSUE TITLE
[Feature] Figure out where the assets are being used

### ISSUE THREAD

**Issue by shailee-m** [creativecommons/chooser#377]
## Description
Find the uses of assets and  `chooser/src/assets/` and also from vocabulary/fonts. Is there a way to decouple them?

## Implementation
- [X] I would be interested in implementing this feature.

CC: @brylie

**Comment by shailee-m** [comment]
@brylie I will inspect the usage and post the updates here.

**Comment by brylie** [comment]
For what it's worth, we are likely to exclude the license images from the `vocabulary-fonts` package, since they are not directly related to fonts.

https://github.com/creativecommons/vocabulary-fonts/pull/2

**Comment by brylie** [comment]
@shailee-m, should we perhaps close this issue?

**Comment by shailee-m** [comment]
@brylie Yes, you're right.
