### ISSUE TITLE
Use FontAwesome package directly rather than getting icons from Vocabulary

### ISSUE THREAD

**Issue by brylie** [creativecommons/chooser#378]
Several FontAwesome icons have been included in the Vocabulary project without attribution. We are in the process of removing the FontAwesome icons from Vocabulary and would like to use the Font Awesome project directly rather than duplicating the fonts in our own source code.

## Task

- [ ] determine where Chooser uses Font Awesome icons, if anywhere
- [ ] replace Vocabulary with Font Awesome as the source for imports
    - either CDN or NPM version, whichever is more appropriate

**Comment by brylie** [comment]
Perhaps we can consider swapping out FontAwesome with a fully open-source icon library, such as [Material Icons](https://fonts.google.com/icons?selected=Material+Icons).

**Comment by MuluhGodson** [comment]
I would love to be assigned here.
