### ISSUE TITLE
[Bug] Deprecation Warnings when compiling the Build Version of Chooser

### ISSUE THREAD

**Issue by MuluhGodson** [creativecommons/chooser#380]
## Description
When building Chooser, there are several deprecation warnings related to the SASS files imported via Bulma and Vocabulary.
>
>```
>Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
>```
>

## Reproduction

1. npm install
2. npm run build
3. See error.

## Expectation
Should build without warnings

## Additional context
- [Breaking changes with Sass Slash-Div](https://sass-lang.com/documentation/breaking-changes/slash-div)

While we may update the new `vocabulary-styles` package to rid these warnings, the warnings stemming from Bulma may potentially remain unresolved but this is not a long term problem since in our project pipeline we will subsequently be deprecating Bulma.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by brylie** [comment]
Added this to the post-launch milestone since it doesn't currently block development.

**Comment by brylie** [comment]
@MuluhGodson, let's see if this issue is resolved by #355
