### ISSUE TITLE
Use `cc-assets` package for CC image assets

### ISSUE THREAD

**Issue by brylie** [creativecommons/chooser#381]
This project uses several Creative Commons image assets, such as license badges and icons. Currently, we are importing those image assets from the Vocabulary project, which has incorrect license terms for our CC Assets.

We have published a new [NPM package called `cc-assets`](https://www.npmjs.com/package/@creativecommons/cc-assets) containing the Creative Commons logos, icons, and license badges along with clarified LICENSE and TRADEMARK texts.

## Task

- [ ] switch to using the `cc-assets` package as the import source for CC image assets

**Comment by MuluhGodson** [comment]
Hello @brylie 
Can I be assigned here?

**Comment by brylie** [comment]
@MuluhGodson you're assigned :-)
