### ISSUE TITLE
Default build output without header and footer

### ISSUE THREAD

**Issue by brylie** [creativecommons/chooser#384]
The current default build output contains a header and footer. Rather the default should only include the Chooser component, without surrounding page elements, since the Chooser is intended to be embedded into other pages/projects.

## Task

- [ ] change the default build output so it doesn't contain a header, breadcrumbs, or footer
- [ ] the default output should only include Chooser sub-components

**Comment by brylie** [comment]
This issue has been partially fixed by modifying the `build-component` command in `package.json` to default to `embedded` mode:

https://github.com/creativecommons/chooser/blob/412c9a053451846c10414828ad7b9835facea2e4/package.json#L18

However, ideally, we wouldn't need the embedded flag.

**Comment by brylie** [comment]
@shailee-m, can we close this issue?

**Comment by shailee-m** [comment]
@brylie Yes

**Comment by shailee-m** [comment]
@brylie I do not have the access to close this issue
