### ISSUE TITLE
Remove unnecessary components from "embedded" build

### ISSUE THREAD

**Issue by brylie** [creativecommons/chooser#387]
The "embedded" build output contains some components that may be undesirable since the intention is to embed the Chooser in an existing page/project. For example, the breadcrumbs and introductory heading/text are seen below.

![image](https://user-images.githubusercontent.com/17307/151136486-1b328b01-4295-4fdf-bce8-d22c3c5216d5.png)

## Task

- [x] determine which sub-components should be included in the embedded output and which should be removed
- [x] remove the unnecessary components from the embedded output

**Comment by MuluhGodson** [comment]
As for what should be removed, I think in the screenshot, the highlighted elements with the faint yellow overlay should be removed in the `embedded production build`, as well as the header and footer component.
