### ISSUE TITLE
[Bug] Issue with localization package

### ISSUE THREAD

**Issue by MuluhGodson** [creativecommons/chooser#408]
## Description
Opening the [License Page](https://stage.creativecommons.org/?page_id=330) on the staging environment for `project_creativecommons.org` displays a blank page with the console error:
```js
i18n.js:4 Uncaught TypeError: Cannot read properties of undefined (reading 'use')
    at Object.9225 (i18n.js:4:5)
    at r (bootstrap:63:22)
    at Object.199c (App.vue:60:1)
    at r (bootstrap:63:22)
    at Module.23be (App.vue?1160:1:1)
    at r (bootstrap:63:22)
    at Module.3dfd (App.vue:1:1)
    at r (bootstrap:63:22)
    at Object.a7c1 (main.js:2:1)
    at r (bootstrap:63:22)
```
I cloned the latest version of this repo and got the same error on my local dev environment. However, `npm run serve` works and displays correctly. 

cc @brylie 

## Reproduction 

1. `npm install`
2. `npm run build-component`
3. Start a local server and serve the newly created `demo.html` file in the `dist` folder [with python3 you can start a local server with `python3 -m http.server`]
4. Open console and See error.

## Expectation
License Chooser should display correctly.

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by brylie** [comment]
Is the `i18n` package missing? Perhaps it is looking for a missing locale file?

**Comment by MuluhGodson** [comment]
@brylie 
Looked more into this issue. It appears our code is correct and works as expected. The localization packages also have no issues. 
The reason for this error is the version of `Vue` imported by the CDN link.
We currently are using 
```js
<script src="https://unpkg.com/vue"></script>
```
which makes available Vue 3 instead of Vue 2. 

Changing this link to 
```js
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
```
solved the issue. So this issue is really a none-issue. False flag.

**Comment by brylie** [comment]
@MuluhGodson, we may need to update our developer documentation in the Chooser package to include the correct example code?

**Comment by brylie** [comment]
I went ahead and updated the README with a Vue 2 code example.
