### ISSUE TITLE
[Bug] Cypress End to End Tests are failing

### ISSUE THREAD

**Issue by Cronus1007** [creativecommons/chooser#447]
## Description
Whenever we try to run the command for running cypress end to end tests all the tests are failing. 
## Reproduction

1. Run the command `npm run test:cypress`
2. All the test cases are failing. \
## Additional context
Have a look at [this comment](https://github.com/creativecommons/chooser/pull/443#issuecomment-1374166059)
## Screenshots
![Screenshot from 2023-02-27 22-12-27](https://user-images.githubusercontent.com/56436023/221626374-8c5f3c37-a1ff-48a4-b06a-e96e2a815792.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Neilblaze** [comment]
@shuguang-lv fyi he already has created a [PR](https://github.com/creativecommons/chooser/pull/448#issuecomment-1442081450) to resolve the same.
