### ISSUE TITLE
[Bug] Adjust positioning of the 'Confused Need Help' and 'Recommended License' sections in mobile view

### ISSUE THREAD

**Issue by soustab10** [creativecommons/chooser#455]
## Description
In mobile view, I think it would be better if the 'Recommended License' section is re-positioned above the 'Confused Need Help' section. In desktop view, it does not cause an issue, but in mobile view I find it meaningless to put that section above the 'Recommended License' section which users need to see to confirm the details of the chosen license.

## Reproduction

1.  Step 1 `https://chooser-beta.creativecommons.org/`
2.  Step 2 Switch to mobile view 
3. Step 3  Fill I know the License I need, then choose a license
4. See that you will always scroll past the 'Confused? Need Help' section.

## Screenshots

![image](https://user-images.githubusercontent.com/95632583/223472978-2d1a7a5d-a47c-4675-ba17-5d5088ea5870.png)

## Environment

 - Device: Mobile Devices

## Additional context

Help sections for the user are generally placed towards the bottom of the page, so this issue will address it as well.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by shuence** [comment]
Hey I would like to work on it, assign me.

**Comment by ZyX-N** [comment]
I would like to work on this task, Can I get assign to this one ?

**Comment by possumbilities** [comment]
@soustab10 Thank you for pointing this out! ❤️ I agree with you, and look forward to your PR!

**Comment by Cronus1007** [comment]
@soustab10 Thanks. Please go ahead with this.
