### ISSUE TITLE
NodeJS version prerequisite required in documentation

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [creativecommons/chooser#458]
## Description
While setting up the project locally with the latest NodeJS version v18.15.0  it gives errors.
which can resolved by downgrading to v14. So, Prerequisite should be there in the readme.

![image](https://user-images.githubusercontent.com/91469717/223944051-40543d5f-185f-4856-bb28-415e061c120b.png)

Adding basic steps like cloning repo to local computer could also be added.

## Reproduction

1.  Clone repo to Local computer
2. Run npm install in the terminal with NodeJS version >14
3. See Error.

## Expectation
Dependencies should be installed without any error.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by soustab10** [comment]
Yes. It should be mentioned somewhere in the `contributing.md` or `readme.md` files.

**Comment by possumbilities** [comment]
@Lakshay-Pruthi I agree, I'd say it should be in the `README.md`.
