### ISSUE TITLE
Upgrade Cypress to latest

### ISSUE THREAD

**Issue by Cronus1007** [creativecommons/chooser#460]
## Description
Right now the version of Cypress used for the E2E testing is v6 while the latest version of cypress is v12. I believe that the Cypress testing should be upgraded since several new features have been implemented especially for Vue.js especially in the version 10.

## Important Links
[Migration Guide for Cypress](https://docs.cypress.io/guides/references/migration-guide)
## Resolution

- [x] I would be interested in resolving this bug.

@possumbilities Would like to know your opinion about it?

**Comment by possumbilities** [comment]
@Cronus1007 My first major concern would be if newer Cypress is going to be compatible with the older version of Vue that's running in the chooser and its related dependencies and whether it makes more sense to do this upgrade after the Vue3 upgrade?

Thoughts?

**Comment by Cronus1007** [comment]
@possumbilities As much as I have worked upon Cypress it is a tool for E2E framework (which obviously depends on the use case one wants to perform with it either frontend or backend). In Chooser we are using it as a frontend tool so it hadn't much to do with the framework used or the version of the framework used. 
The main reason I am proposing it is the reason of a new feature called initSpecRoutine since the version which we are using right now doesn't have a great support for before, beforeAll, after and afterAll functionsfunctions as compared to that of the older version. Additionally we can test the application on Firefox browser as well so such reasons are prime reason why I would like to have an upgrade.

**Comment by possumbilities** [comment]
@possumbilities I'm fine with this if there's data to support (even just testing it) that it won't break. My concern was node version conflicts between technologies.

**Comment by Cronus1007** [comment]
@possumbilities I dont have any data to support it. One thing which we can do is by just testing it out whether cypressv12 is going to be compatible with nodev14. And then you can test it on your local enviornment. In my opinion it will be we just need to tweak code a little bit i.e. introduce the hooks like before, beforeAll, after and afterAll statements.
