### ISSUE TITLE
Improper padding in "Confused? Need Help?" modals

### ISSUE THREAD

**Issue by soustab10** [creativecommons/chooser#464]
## Description
The modal containing the solutions to the questions in `Confused? Need Help?` section has improper padding which is particularly visible in mobile view and affects user experience. 

## Reproduction

1. Step 1: Go to https://chooser-beta.creativecommons.org/
2.  Step 2: Click on any question under  `Confused? Need Help?` section (preferably in mobile view)
3. See inappropriate padding.

## Expectation
The content in the modal should have proper padding.

## Screenshots
![image](https://user-images.githubusercontent.com/95632583/225329249-3600dbb5-6154-4223-9655-658da6ccaa0f.png)

## Environment

 - Device: Mobile

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by AK4266** [comment]
I would like to work on this issue

**Comment by possumbilities** [comment]
@soustab10 You've done a tremendous job outlining Issues as contributions, and we're very grateful! ❤️ 

@AK4266 Would you still like to work on a PR for this?

**Comment by AK4266** [comment]
@possumbilities yes, I'm willing to work on this issue

**Comment by Cronus1007** [comment]
@AK4266 I have assigned you this issue. Please go ahead.

**Comment by codewithmide** [comment]
> @AK4266 I have assigned you this issue. Please go ahead.

@AK4266 Please confirm if you are currently working on this issue. If yes, are you open for collaborations?

**Comment by AK4266** [comment]
@codewithmide Yes, i'm working on the issue and i'm open for collaborations. Just want to know what kind of collaborations are you talking about?

**Comment by codewithmide** [comment]
> > > @codewithmide Yes, i'm working on the issue and i'm open for collaborations. Just want to know what kind of collaborations are you talking about?
> > 
> > Thank you for your response. I intend on collaborating with on this issue. Since there are few active issues
> 
> Lets do it
> 

Great! Are you on cc slack channel? Let's have a conversation

**Comment by shuence** [comment]
@AK4266 I fixed this issue Should I submit PR If you haven't fixed this yet ?

**Comment by AK4266** [comment]
> @AK4266 I fixed this issue Should I submit PR If you haven't fixed this yet ?
No, i wasn't can you share me the link

**Comment by AK4266** [comment]
> @AK4266 I fixed this issue Should I submit PR If you haven't fixed this yet ?

Yeah, go ahead and submit PR

**Comment by shuence** [comment]
Okay
