### ISSUE TITLE
Disable scroll on body of website when modal is active.

### ISSUE THREAD

**Issue by soustab10** [creativecommons/chooser#473]
## Description
When a modal is active, scrolling is still active on the body of the website - which is not particularly a good user experience. It is particularly noticeable in ` [the terms and intended legal effect of CC0,]` modal under `Waiver Your Copyright`.

## Reproduction

1.  Step 1: Go to [website](https://chooser-beta.creativecommons.org) .
2.  Step 2: Click on any question under `CONFUSED? NEED HELP?` section.
3. Scroll and see error.

## Expectation
The body should stay fixed when any modal is open.

## Screenshots

https://user-images.githubusercontent.com/95632583/227338180-629afddb-75d6-42d4-89e2-e3251e13c454.mp4

## Environment

 - Device: Desktop Screens

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Cronus1007** [comment]
@soustab10 Everything is appearing to be fine for me.Am I missing something?

**Comment by soustab10** [comment]
> @soustab10 Everything is appearing to be fine for me.Am I missing something?

I think the scroll action while the modal is active degrades the user experience. What do you think of it?

**Comment by SADIK112** [comment]
@soustab10 - [https://github.com/creativecommons/chooser/pull/482](url)
Made this PR to resolve this issue and disable scroll when the modal gets active.

**Comment by nik132-eng** [comment]
if this issue is not fixed i want to fix this can you please assign me this issue?
