### ISSUE TITLE
[Bug] Fix Typo in FAQs

### ISSUE THREAD

**Issue by Xaid-vfx** [creativecommons/chooser#476]
## Description
There is unnecessary right parenthesis character as highlighted in the picture below:

<img width="725" alt="Screenshot 2023-03-29 at 4 34 57 PM" src="https://user-images.githubusercontent.com/77684943/228568751-35001fbd-4437-4f38-a64c-465ef6233425.png">

## Reproduction

1. Go to https://chooser-beta.creativecommons.org/
2. Scroll down to `Confused? Need help?`
3. Click on `What Are Creative Commons Licenses?`
4. See error in Modal.

## Expectation
Remove the right parenthesis to fix typo.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
@Xaid-vfx good spot. You've got a few more contributions. Would anyone else like to correct this?

**Comment by Cronus1007** [comment]
@kartiksprajapati  Are you willing to take up this issue?

**Comment by UlbertAO** [comment]
I can work on this

**Comment by UlbertAO** [comment]
Have raised PR for the same [#478](https://github.com/creativecommons/chooser/pull/478)

**Comment by shuence** [comment]
I would be happy to work on this

**Comment by kartiksprajapati** [comment]
> @kartiksprajapati Are you willing to take up this issue?

Yes, I'm ready to work upon this.

**Comment by Xaid-vfx** [comment]
Hey @kartiksprajapati @UlbertAO ,
Good to see your enthusiasm for contributions, keep up the good work. Although, there are certain rules to be followed while making a contribution. One of which is you are only supposed to make a PR, when you are assigned to work on an issue. As of now, nobody is assigned for the issue.
Wait till maintainers assign someone to work on this issue and then make a PR. For now, please close both the PRs raised for this issue and wait till maintainers assign you for the same.
Read [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/) to know better.
 Also, this is beginner friendly issue, I would recommend someone who is a beginner to take up this issue.

**Comment by AK4266** [comment]
I'm willing to work on this issue can you assign it to me

**Comment by Pursottam6003** [comment]
> @Xaid-vfx good spot. You've got a few more contributions. Would anyone else like to correct this?

I would like to work on this issue if possible please assign me

**Comment by moechadSayshi** [comment]
is this issue worked upon right now by someone ?

**Comment by Xaid-vfx** [comment]
@possumbilities since no one is assigned to this issue. Could I fix this?
