### ISSUE TITLE
[Feature] The Growing Common Sections looks so messed up

### ISSUE THREAD

**Issue by 0xJaskeerat** [creativecommons/chooser#487]
## Problem

I was going through the [The creative commons , growing common section](https://creativecommons.org/#:~:text=THE-,GROWING,-COMMONS)  and I was not at all impressed by the messed up gallery
Everything is so sticky with no margins and padding around them, the UI experience is bad for a new user

## Description

What I think is we should be focussing on the design and then UI development of this gallery section 

Here are the screenshots where I felt the UI disconnect
<img width="1440" alt="Screenshot 2023-08-01 at 7 18 08 PM" src="https://github.com/creativecommons/chooser/assets/124770018/7b61d8da-e097-46d5-9568-eeac6acc25b4">

<img width="1440" alt="Screenshot 2023-08-01 at 7 18 23 PM" src="https://github.com/creativecommons/chooser/assets/124770018/94f24081-2ce8-4a01-8b3e-18a0a4f7df7c">

## Alternatives

Here are few solutions according to me 
* Fix the margins and padding between each of the common component 
* Put less content in a single row , maybe 6 commons in big devices , 4 in medium devices like laptops and tabletsand , 1 in mobile devices
* We can use scroll animations to make the gallery more presentable maybe using Framer Motion

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by nsundriyal62** [comment]
this bug seems easy to solve
i am new to open source 
can i do it?

is there any assign process or should i directly generate a PR

**Comment by 0xJaskeerat** [comment]
@nsundriyal62 Hey buddy , I am working on it

**Comment by nsundriyal62** [comment]
@0xJaskeerat ok sir.................

;)

**Comment by possumbilities** [comment]
@0xJaskeerat thank you for your enthusiasm here! 

This change affects the current design, however a new design utilizing [Vocabulary](https://github.com/creativecommons/vocabulary) is in progress. If this area was to migrate into the new design, solutions here may be carried over, so I'm putting this as a blocked item, and making it a discussion instead for now.
