### ISSUE TITLE
[Bug] Creative Commons Icons are missing in Copy Area

### ISSUE THREAD

**Issue by beckej13820** [creativecommons/chooser#495]
## Description
No matter what license is chosen in the Creative Commons Chooser, the icons represented always default to CC-BY.
## Reproduction
1. Use the beta chooser at https://chooser-beta.creativecommons.org/
2. This bug works whether you go through the questions in the chooser or if you say I know what license I want.
3. Select any creative commons license other than CC0 or CC-BY
4. See error. In the copy and pastable area at the bottom right corner, missing the icons after CC-BY. So a CC-BY-SA license will have the CC and BY, but be missing the SA.

## Expectation
I would expect the icons in the copy and paste area to match the icons for the license
## Screenshots
Here are a couple screenshots

CC-BY-SA - Screenshot shows that the license is set to CC-BY-SA but is missing the SA icon
<img width="561" alt="Screenshot 2023-10-29 at 10 12 55 PM" src="https://github.com/creativecommons/chooser/assets/29982981/f5abd61b-b64a-4013-9a04-95a36910f5eb">

CC-BY-ND - Screenshot shows that the license is set to CC-BY-ND but is missing the ND icon
<img width="1146" alt="Screenshot 2023-10-29 at 10 14 45 PM" src="https://github.com/creativecommons/chooser/assets/29982981/17ba7157-9e01-44b6-97d2-ff4926e18e6a">

## Environment

 - Device: Mac Laptop M1 chip (2020)
 - OS: OS 13.2.1
 - Browser: Chrome
 - Version: 118.0.5993.88 
 - Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by dotarjun** [comment]
Hey, can you assign this to me

**Comment by dotarjun** [comment]
Hey. I am having trouble setting up the repo on my dev environment. 

after ``npm install``

I do this and run into an error

```
❯ npm run serve

> @creativecommons/chooser@0.2.0 serve
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/2 modules 0 active(node:14865) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
10% building 2/4 modules 2 active /home/arjun/programming/OpenSource/chooser/node_modules/webpack-dev-server/client/index.js?http://192.168.0.108:8080&sockPath=/sockjs-nodenode:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/arjun/programming/OpenSource/chooser/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/arjun/programming/OpenSource/chooser/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/arjun/programming/OpenSource/chooser/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/arjun/programming/OpenSource/chooser/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/arjun/programming/OpenSource/chooser/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/arjun/programming/OpenSource/chooser/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/arjun/programming/OpenSource/chooser/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/arjun/programming/OpenSource/chooser/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/arjun/programming/OpenSource/chooser/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/arjun/programming/OpenSource/chooser/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/arjun/programming/OpenSource/chooser/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.18.0
```

**Comment by dotarjun** [comment]
It's already assigned to me. Do you mind lending me a hand in setting up the dev environment?

**Comment by lalitkumawat1m** [comment]
Hey @dotarjun are still working on this issue or can I take it

**Comment by dotarjun** [comment]
Im working

**Comment by BalrajDhakad** [comment]
is it still open can i start working on it?
