### ISSUE TITLE
"Copy this code [...]" boxes: Actual selection may differ from previewed selection

### ISSUE THREAD

**Issue by Chealer** [creativecommons/chooser#537]
If I go to https://creativecommons.org/choose/?lang=en and try selecting - for example - a URL in the "Copy this code to let your visitors know!" textarea, the previewed selection matches the fragment I'm trying to select, but when I release the primary mouse button, it turns out the actual selection is the whole textarea's content.

In report creativecommons/creativecommons.org#681, Rob Myers stated that it was intentional that the whole content is selected even when the user tries selecting a fragment. If that is correct, the solution would be to properly reflect what will happen between the time the button is pushed and the time it is released.

**Comment by possumbilities** [comment]
Closing this issue as it relates to the previous version of the chooser and not the Chooser Beta.
