### ISSUE TITLE
[Bug] The closing button for the "Confused need help " pop up pages is aligning with the cc logo

### ISSUE THREAD

**Issue by akshathere** [creativecommons/chooser#546]
## Description
When we are clicking on the popup blogs for the "Confused need help" links the closing button of those blogs are aligning with the cc logo

## Reproduction

1. Scroll to the end of the [site](https://chooser-beta.creativecommons.org/) to see the Confused need help
2. Click on any of these links
3. A pop up will open with the logo of cc and closing button on top right aligning
4. See error.

## Expectation
We can move the logo to the left top corner of the box and keep the closing button on right top corner only
## Screenshots
![{BB9A77D8-43C9-4FF8-A301-0196CAE96D95}](https://github.com/user-attachments/assets/4c27b914-5563-4da4-9a2d-a05a6556d3c2)

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by akshaytyagi482** [comment]
can you assign this to me i can fix it up.

**Comment by jey-exp** [comment]
I am willing to work on this issue, can I work on it and raise a PR?
I have set-up the project locally, but I need some help regarding the structure of the project, where can I seek help?
