### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by akmadian** [creativecommons/chooser#58]
The chooser needs to be available in languages other than english before it's launched. This translation with be done with [Transifex](https://www.transifex.com/). Transifex integration needs to be coordinated with CC Engineering before it goes live.

**Comment by akmadian** [comment]
Transifex may be integrated, will be able to test integration after some translations are 100% reviewed and first PR is received.

**Comment by Cronus1007** [comment]
@akmadian For internalization `i18n` can be a preffered npm library and I would like to work on this issue.

**Comment by obulat** [comment]
@Cronus1007, this is a stale issue.
Closing this issue as i18n and Transifex have already been integrated into the Chooser.
