### ISSUE TITLE
Rewrite Unit/ e2e tests

### ISSUE THREAD

**Issue by akmadian** [creativecommons/chooser#99]
The current unit and e2e tests were written before the current Outreachy internship round, and need to be updated for the current codebase. We need unit tests for components and utils, but some components won't need tests because they mock Vocabulary components, and will be deprecated soon.

Unit tests are done with [Jest](https://jestjs.io/), and e2e tests are done with [nightwatch](https://nightwatchjs.org/).

This task is partially blocking #77. The reason for the block was that the tests written at the time the PR was created were old and would always fail. Once we've got some tests updated, we can merge it.

The components that need tests are:
- [x] AttributionDetailsStep (#112)
- [x] CopyrightWaiverStep (#113)
- [x] DropdownStep (#114)
- [x] FirstStep (#115)
- [x] HelpSection (#116)
- [x] LicenseCode (#117)
- [ ] LicenseCopy (#122)
- [x] LicenseDetailsCard (#118)
- [x] LicenseDropdown (#120)
- [ ] LicenseUseCard (#121)
- [x] Step (#123)
- [x] Stepper (#126)
- [x] App (#124)
- [x] All methods in `./src/utils/license-utilities.js` (#125)

**Note that this specific issue is not up for grabs, and is meant to track meta discussion about the larger task of creating tests as a whole.**

**Comment by obulat** [comment]
I think we should also add a test for Vuex store, @akmadian .

**Comment by jperl** [comment]
👋 Hello I maintain an [open source library](https://github.com/qawolf/qawolf) that generates [Playwright](https://github.com/microsoft/playwright) code. I would be happy to submit PRs setting up e2e tests, if you are cool with them using Playwright?

**Comment by akmadian** [comment]
@obulat I agree, I'll open an issue for it :)

@jperl thanks for letting us know, but I think we'll stick with nightwatch

**Comment by Cronus1007** [comment]
@obulat  Just a suggestion shall we implement `cypress` for getting the code coverage and as per my observation code coverage tool is missing in the repo.

**Comment by Cronus1007** [comment]
@obulat  There is a need to reopen the issues down 
> The current unit and e2e tests were written before the current Outreachy internship round, and need to be updated for the current codebase. We need unit tests for components and utils, but some components won't need tests because they mock Vocabulary components, and will be deprecated soon.
> 
> Unit tests are done with [Jest](https://jestjs.io/), and e2e tests are done with [nightwatch](https://nightwatchjs.org/).
> 
> This task is partially blocking #77. The reason for the block was that the tests written at the time the PR was created were old and would always fail. Once we've got some tests updated, we can merge it.
> 
> The components that need tests are:
> 
> * [x]  AttributionDetailsStep (#112)
> * [x]  CopyrightWaiverStep (#113)
> * [x]  DropdownStep (#114)
> * [x]  FirstStep (#115)
> * [x]  HelpSection (#116)
> * [x]  LicenseCode (#117)
> * [ ]  LicenseCopy (#122)
> * [x]  LicenseDetailsCard (#118)
> * [x]  LicenseDropdown (#120)
> * [ ]  LicenseUseCard (#121)
> * [x]  Step (#123)
> * [x]  Stepper (#126)
> * [x]  App (#124)
> * [x]  All methods in `./src/utils/license-utilities.js` (#125)
![Screenshot from 2021-01-11 18-21-07](https://user-images.githubusercontent.com/56436023/104185613-3392e280-543b-11eb-887d-7f15b8a20200.png)

**Comment by obulat** [comment]
Closing this issue as this is very old, and the code has changed a lot since this issue was opened.
